/* Research annotations, not a surveyed access network. No survey mutations. */
window.ACCESSIBILITY_DATA={
 version:'2026-09-15-1',
 sources:{
  osm:{title:'Preserved OSM extract · 2026-09-13',url:'https://www.openstreetmap.org/copyright',scope:'398 displayed road/footway records. Source geometry and tags, not a current accessibility audit.'},
  brief:{title:'Course lecture · design the ground first',url:'accessibility-research.html#course',scope:'Workspace lecture notes, p.9: slope, drainage, bridge landing, stopping and service conflicts.'},
  dft:{title:'DfT · Inclusive Mobility (2022)',url:'https://www.gov.uk/government/publications/inclusive-mobility-making-transport-accessible-for-passengers-and-pedestrians',scope:'UK comparative design guidance. Not Lebanese legal certification.'},
  prowag:{title:'US Access Board · pedestrian access routes',url:'https://www.access-board.gov/prowag/technical.html',scope:'Comparative continuous-route and kerb-transition framework, not applicable local code.'},
  maraach:{title:'UN-Habitat · Maraach improvements (2022)',url:'https://unhabitat.org/news/09-nov-2022/urban-october-in-beirut-improving-life-through-urban-interventions',scope:'Another Bourj Hammoud subarea: lighting and drainage affected everyday access. Not a survey of our plot.'},
  photo:{title:'Existing bridge-angle screenshot · April 2023 imagery',url:'pictures-auto-evidence/2026-09-13/64-m9-bridge-oblique.png',scope:'Historical view from Armenia bridge. Surface joints/vegetation and rail visible; no dimensions or current condition inferred.'}
 },
 kinds:{steps:{label:'S · Source-mapped steps',color:'#ad453b'},check:{label:'? · Continuity needs checking',color:'#a26b20'},comfort:{label:'C · Sensory / rest checks',color:'#755394'},arrival:{label:'A · Arrival / service study',color:'#327b97'},project:{label:'P · Project design responsibility',color:'#236e61'}},
 journeys:{
  all:{title:'A connection is not yet a usable journey',text:'Read the full chain: approach → crossing → landing → clear pavement → entrance → destination. One unresolved link can prevent independent access.',ids:null},
  south:{title:'From the lower / southern neighbourhood',text:'Street 52 brings the study toward C1, but mapped stairs interrupt a step-free interpretation. C2 also has steps. No verified step-free highway crossing is established here.',ids:['X1','X2','X3','X4','X8','X9','X10','X11','X14','P']},
  north:{title:'From the upper / northern side',text:'Being on the same side of the highway avoids that crossing; it does not establish a continuous sidewalk. Check Street 80, driveways, the bend and final threshold.',ids:['X5','X6','X7','X8','X10','X11','X12','X13','X14','P']},
  west:{title:'From the river / western side',text:'Armenia is a mapped road bridge, not a certified accessible pedestrian link. Rail, surface, usable edge width and onward junctions need a continuous check.',ids:['X6','X7','X8','X10','X11','X13','X14','P']}
 },
 zones:[
  {title:'SOUTH / bridge + approach',ring:[[33.8951,35.5397],[33.8951,35.5417],[33.8964,35.5417],[33.8964,35.5397]],kind:'check'},
  {title:'NORTH / same-side approach',ring:[[33.8968,35.5409],[33.8968,35.5422],[33.898,35.5422],[33.898,35.5409]],kind:'check'},
  {title:'FINAL INTERFACE / design study',ring:[[33.89625,35.54072],[33.89625,35.54157],[33.89692,35.54157],[33.89692,35.54072]],kind:'project'}
 ],
 routes:[
  {title:'C1 pedestrian bridge · source geometry',kind:'arrival',ways:[701135687],note:'Bridge deck geometry only; approach steps mapped separately.'},
  {title:'Mapped steps · C1 and C2 approaches',kind:'steps',ways:[270786366,701135688,1069243890,1069243891],note:'Source says highway=steps. Condition and alternative provision VERIFY.'},
  {title:'C2 · bridge with mixed crossing tags',kind:'arrival',ways:[1069243892],note:'bridge=yes + layer=1 + crossing=zebra. Do not interpret as an at-grade highway zebra.'},
  {title:'Street 52 / Street 80 · road centrelines',kind:'check',ways:[306996681,715531021,275315121],note:'Not sidewalk geometry, not a recommended walking route. Width, kerbs and continuity TBD.'},
  {title:'Armenia bridge · road components',kind:'check',ways:[452148075,452148076],note:'Road bridge present; pedestrian usability and onward connections not established.'}
 ],
 tags:[
  {id:'X1',title:'C1 · southern stair approach',kind:'steps',at:[33.89588,35.54086],ways:[270786366],fact:'The preserved source marks steps at the southern end of the nearest pedestrian bridge.',meaning:'A bridge on the plan does not establish access for a wheelchair, stroller or wheeled load. This is a mapped stair condition, not proof that every alternative is absent.',design:'Do not make the project’s inclusion claim depend on this bridge alone. Investigate a continuous step-free alternative with the responsible authority.',check:'Photograph the entire approach, landings, handrails, any ramp/lift and its operation. Do not derive rise or gradient from the plan.',sources:['osm','prowag']},
  {id:'X2',title:'C1 · northern landing to plot',kind:'steps',at:[33.89640,35.54104],ways:[701135688],fact:'Steps are also tagged on the northern side. The site lies close to this approach on the preserved plan.',meaning:'The end of the bridge and the start of a usable entrance are different places. Nearness can hide a kerb, narrow turn, vehicle movement or change of level.',design:'Draw a ground section from the landing toward the proposed public entrance; reserve a clear waiting/turning area without claiming ownership of the pavement.',check:'Measure landing level, clear width, crossing of vehicle access and continuity to the site boundary.',sources:['osm','brief']},
  {id:'X3',title:'C2 · an alternative, not a verified solution',kind:'steps',at:[33.89477,35.54644],ways:[1069243892,1069243890,1069243891],fact:'The eastern crossing has bridge=yes, layer=1 and crossing=zebra together; both associated approaches are tagged steps.',meaning:'A naive map could incorrectly draw a street-level zebra or call this a step-free detour. Neither conclusion is supported.',design:'Keep the alternative in the urban study but do not advertise it as independently usable until its approaches and onward journey are checked.',check:'Resolve the conflicting tags against current imagery and a safe site visit; check both ends and any lift/ramp. No crossing-time estimate yet.',sources:['osm','prowag']},
  {id:'X4',title:'Street 52 · the journey before the bridge',kind:'check',at:[33.89526,35.54070],ways:[306996681,715531021],fact:'Two one-way road components connect the southern street system toward the highway edge. Their tags do not describe usable pavement width.',meaning:'Vehicle connectivity can look strong while the pedestrian strip remains unknown. The narrowest usable point matters more than the street’s total width.',design:'Study continuity on both sides before choosing an arrival side. Do not convert road centrelines into pedestrian directions.',check:'Walk each pavement edge: pinch points, driveways, surface breaks, parked vehicles, poles and legal crossings. Record actual dimensions.',sources:['osm','dft']},
  {id:'X5',title:'Street 80 · same side is not enough',kind:'check',at:[33.89728,35.54167],ways:[275315121],fact:'Street 80 is a two-lane, one-way tertiary road in the extract; its southern curve runs beside the site.',meaning:'Northern visitors may avoid the highway crossing, yet still encounter a broken approach chain. One-way is a vehicle tag, not a pedestrian prohibition.',design:'Compare a Street 80-facing entrance with the bridge-side arrival. Choose after testing pavement continuity, levels and service conflicts.',check:'Survey both street edges and every driveway. Check where the northern approach actually connects; do not bridge gaps in the source with invented lines.',sources:['osm','brief']},
  {id:'X6',title:'Armenia bridge · width that can be used',kind:'check',at:[33.89538,35.53711],ways:[452148075,452148076],fact:'Two mapped road-bridge components cross the river. Existing April 2023 imagery shows a railing, pavement joints and vegetation at the viewing position.',meaning:'A visible pedestrian edge is useful evidence, but a perspective photograph cannot prove clear width, crossfall or current maintenance.',design:'Treat the river crossing as a route to audit, not an accessible gateway already secured by the map.',check:'Measure the clear strip and level changes; verify surface continuity and both onward junctions. Photograph safely from pedestrian space.',sources:['osm','photo','dft'],photo:'pictures-auto-evidence/2026-09-13/64-m9-bridge-oblique.png'},
  {id:'X7',title:'Onward junctions · no invisible links',kind:'check',at:[33.89551,35.53819],fact:'Local roads continue east of the river bridge. Our base does not supply a continuous kerb-to-kerb pedestrian audit.',meaning:'A small gap between two drawn components may represent the hardest part of a journey: a turn, a crossing or an obstructed corner.',design:'Assess complete arrival options, including their return direction, rather than highlighting isolated favourable segments.',check:'At each turn record crossing provision, sight lines from seated height, kerb transitions and the side reached. Signal timing only if a signal exists.',sources:['osm','prowag']},
  {id:'X8',title:'Plot-side bend · slow entry versus movement',kind:'arrival',at:[33.89629,35.54118],ways:[275315121],fact:'The mapped Street 80 bend passes near the plot’s southern/eastern approach and the bridge landing.',meaning:'Turning traffic, someone pausing to orient themselves and an entrance queue could compete here. This is a conflict hypothesis, not an observed crash site.',design:'Keep door swing, queuing and waiting out of the walking line. Test a recessed forecourt and separate service manoeuvring without placing either on the highway.',check:'Observe turning vehicles, deliveries and pedestrian waiting in several time bands. Measure space before locating a driveway or drop-off.',sources:['osm','brief']},
  {id:'X9',title:'Southern rest / exposure check',kind:'comfort',at:[33.89564,35.54034],fact:'The plan locates an approach to the highway, but does not establish seating, usable shade or night-time lighting continuity.',meaning:'Someone can be able to walk yet unable to complete a journey without rest. A short distance alone is not an adequate access test.',design:'Test rest opportunities along the approach and sheltered waiting at the project. Seats should not obstruct the continuous clear route.',check:'Log actual shade at visit time, seats with back/arm support, companion space, glare and light continuity. No lux or heat value inferred.',sources:['dft','maraach']},
  {id:'X10',title:'Can the entrance be found and understood?',kind:'comfort',at:[33.89662,35.54140],fact:'The plot is a small destination beside major movement infrastructure; the new building’s entrance and signs are not designed yet.',meaning:'A visually dramatic façade can still fail a first-time visitor or someone who cannot rely on hearing traffic or reading small signs.',design:'Make the public entrance identifiable before the decision point. Use consistent contrast, plain-language information and more than a colour-only cue; test appropriate local languages with users.',check:'Trace the approach with people with different sensory and cognitive access needs. Measure lighting later; do not equate illumination with glare-free legibility.',sources:['dft','brief']},
  {id:'X11',title:'Street → threshold → useful destination',kind:'project',at:[33.89666,35.54117],fact:'The aligned plot boundary is known schematically; surveyed entrance levels and the final building plan are TBD.',meaning:'A ramp to a door is not the end of accessibility. Reception, toilets, shared rooms and any upper public level must remain part of the journey.',design:'Test one dignified public arrival used together, level changes resolved in section, usable doors and independently reachable public functions. Plan accessible exit/evacuation with the applicable authority.',check:'Commission spot levels and check applicable local requirements before fixing gradients, thresholds, lifts, doors or egress dimensions.',sources:['brief','dft']},
  {id:'X12',title:'Delivery / loading is a separate access need',kind:'arrival',at:[33.89700,35.54153],ways:[275315121],fact:'Workshop/industrial context and the road approach make servicing relevant; exact delivery hours, vehicle sizes and loading positions are unverified.',meaning:'Moving stock through the same place where visitors stop can undo an otherwise good entrance. A wide road does not guarantee loading permission.',design:'Compare a separated service edge and timed deliveries; test actual vehicle swept paths only after obtaining vehicle and authority requirements.',check:'Ask nearby operators about delivery vehicles and duration. Observe manoeuvres and whether the clear pedestrian strip stays open.',sources:['brief','osm']},
  {id:'X13',title:'Taxi / bus / assisted arrival · location TBD',kind:'arrival',at:[33.89687,35.54151],fact:'No accessible stopping bay or operational bus stop at this tag has been verified. This marker is an inspection question, not a stop.',meaning:'Being dropped near the building is insufficient if the passenger exits into traffic, cannot reach the pavement or must negotiate another barrier.',design:'Investigate a lawful, usable set-down connection to the same entrance. Do not designate highway stopping or rely on a helper carrying someone.',check:'Verify actual transport services, stop locations, boarding arrangements, kerb-to-door continuity and permitted stopping with operators/authority.',sources:['dft','prowag']},
  {id:'X14',title:'Wet weather / evening / maintenance',kind:'comfort',at:[33.89652,35.54095],fact:'The plot-side levels, drainage performance and lighting have not been measured. UN-Habitat documented everyday access improvements from lighting and drainage elsewhere in Maraach.',meaning:'A route that works in one dry daytime photograph may fail after rain, after shutters close or when objects are moved onto it.',design:'Keep drainage away from the entrance line, maintain a clear walking strip and provide legible after-hours access to whichever project layer stays open.',check:'Repeat the approach in daylight and early evening, and inspect drainage after rain when safe. Record date, obstructions and operation rather than calling a place permanently safe/unsafe.',sources:['maraach','brief']},
  {id:'P',title:'Our plot · protect without excluding',kind:'project',at:[33.89653,35.54112],fact:'The plot sits north of the main highway, east of the river and beside Street 80 and C1’s northern approach in our preserved base.',meaning:'Nesting must reduce exposure without turning the protected centre into a raised, hidden or difficult-to-enter destination.',design:'Use an accessible, sheltered threshold as the first nest; then a legible shared space and quieter inner rooms. Protection comes from position, enclosure and buffering, not a compulsory stair or maze.',check:'Compare entrance sections from both likely approaches. Verify levels and responsibilities; retain access when outer public spaces are open but inner rooms are closed.',sources:['osm','brief']}
 ]
};
