/* Read-only accessibility study. Deliberately no localStorage, IndexedDB or sync writes. */
window.createAccessibility=function(api){
 'use strict';
 const D=window.ACCESSIBILITY_DATA,B=window.PICTURES_NEW_DATA,C=window.CONNECTIONS_DATA;
 const renderer=L.canvas({padding:.35}),base=L.layerGroup(),overlay=L.layerGroup(),pins=L.layerGroup(),leaders=L.layerGroup(),focus=L.layerGroup();
 let active=false,built=false,journey='all',sourceOnly=false,zones=true,selected=null,markers={};
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shell=document.getElementById('map').parentElement,panel=document.createElement('section');panel.id='accessibility-panel';panel.hidden=true;panel.setAttribute('aria-label','Accessibility analysis');
 panel.innerHTML='<header><div><h2>Accessibility</h2><small>05 / The whole arrival, not just the bridge</small></div><button id="ax-collapse" aria-expanded="true" aria-label="Collapse accessibility panel">−</button></header><div id="ax-body">'+
 '<p class="ax-status">DESK ANALYSIS · NO CERTIFIED ACCESSIBLE ROUTE</p><label class="ax-select">Compare an approach<select id="ax-journey"><option value="all">All approaches</option><option value="south">Lower / southern neighbourhood</option><option value="north">Upper / northern side</option><option value="west">River / western side</option></select></label><div id="ax-summary" aria-live="polite"></div>'+
 '<ol class="ax-chain" aria-label="Whole journey"><li>Approach</li><li>Crossing</li><li>Landing</li><li>Clear pavement</li><li>Entrance</li><li>Destination</li></ol>'+
 '<label class="ax-check"><input id="ax-source" type="checkbox"> Mapped components only · hide inspection tags</label><label class="ax-check"><input id="ax-zones" type="checkbox" checked> Tint buildings in inspection areas</label>'+
 '<div class="ax-actions"><button id="ax-fit">Fit study</button><button id="ax-plot">Our plot</button></div><p class="ax-small">Solid red = source-mapped steps. Dashed amber = road components to inspect, NOT walking directions. Shading = study windows, not an access rating.</p><div id="ax-detail" aria-live="polite"></div><div id="ax-list"></div>'+
 '<details><summary>What the source can—and cannot—tell us</summary><div id="ax-inventory"></div><p>Missing tags do not mean missing sidewalks. Road surfaces do not describe the pavement. Node-level features and separately mapped objects require their own audit.</p><p>C2 has bridge/layer and zebra-crossing tags together. We preserve the uncertainty; no at-grade highway crossing is drawn.</p></details>'+
 '<details><summary>Different people, different obstacles</summary><ul><li>Wheelchair, stroller or wheeled load: continuous level changes, clear turning and passing.</li><li>Limited walking endurance: distance between usable resting places, not distance alone.</li><li>Low vision or first visit: consistent edges, contrast and information before a decision.</li><li>Hearing / cognitive access needs: do not rely on sound, colour or complex instructions alone.</li><li>Children and companions: room to wait together away from moving vehicles.</li></ul><p>These are design tests, not a count or diagnosis of local residents.</p></details>'+
 '<details><summary>Who can resolve which part?</summary><p><b>Project:</b> entrance, levels within the site, sheltered waiting, service separation and internal access.</p><p><b>Street authority + neighbours:</b> pavement continuity, driveways, kerbs, drainage and stopping.</p><p><b>Infrastructure / transport authorities:</b> bridge access, crossing operation and transport boarding.</p><p>No external works or permissions are assumed.</p></details>'+
 '<details><summary>Priority field checks</summary><ol><li>X1–X2: both bridge approaches and any step-free alternative.</li><li>X5–X8–X11: Street 80 to the entrance, including levels and the bend.</li><li>X4 and X6–X7: complete southern and western approaches.</li><li>X9–X10–X14: rest, legibility, drainage and evening operation.</li><li>X12–X13: deliveries, actual transport stopping and boarding.</li></ol><a href="accessibility-research.html#field-plan" target="_blank" rel="noopener">Field sheet and measurable evidence ↗</a></details>'+
 '<details><summary>Sources / scope</summary><div id="ax-sources"></div></details><p><a href="accessibility-research.html" target="_blank" rel="noopener">Full analysis, journey matrix & design decisions ↗</a></p><p class="ax-small">Original survey, photographs and building assignments remain unchanged. UK/US guidance is comparative; applicable local requirements remain VERIFY.</p></div>';
 shell.appendChild(panel);L.DomEvent.disableClickPropagation(panel);L.DomEvent.disableScrollPropagation(panel);
 const key=document.createElement('div');key.id='accessibility-key';key.hidden=true;key.innerHTML='<b>USABLE JOURNEY / 05</b>'+Object.values(D.kinds).map(k=>'<span><i style="background:'+k.color+'"></i>'+esc(k.label)+'</span>').join('')+'<small>Tags = research stations, not amenities.<br>Teal = responsibility, NOT confirmed access.<br>Dotted leaders only reposition labels.</small>';shell.appendChild(key);L.DomEvent.disableClickPropagation(key);
 const caption=document.createElement('div');caption.id='accessibility-caption';caption.hidden=true;caption.innerHTML='↑ NORTH / UPPER · road centrelines ≠ usable sidewalks<br><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a> · preserved geometry';shell.appendChild(caption);
 const $=id=>document.getElementById(id),tags=()=>sourceOnly?[]:D.tags.filter(t=>!D.journeys[journey].ids||D.journeys[journey].ids.includes(t.id));
 function padding(){return innerWidth<700?{paddingTopLeft:[40,50],paddingBottomRight:[18,panel.offsetHeight+20]}:{paddingTopLeft:[65,65],paddingBottomRight:[panel.offsetWidth+45,65]};}
 function fit(){api.map.invalidateSize();const pts=tags().map(t=>t.at);api.map.fitBounds(pts.length?L.latLngBounds(pts).pad(.12):B.bounds,{...padding(),animate:false,maxZoom:18});}
 function build(){if(window.BuildingMap){BuildingMap.base(base,renderer);return;}if(built)return;B.base.forEach(f=>{if(!f.building&&f.polygon)L.polygon(f.polygon,{stroke:false,fillColor:f.color==='#2469b9'?'#c5dce5':'#e5e9e1',fillOpacity:1,interactive:false,renderer}).addTo(base);});B.buildings.forEach(b=>L.polygon(b.rings,{color:'#869799',weight:.65,fill:false,opacity:.65,interactive:false,renderer}).addTo(base));C.ways.forEach(w=>L.polyline(w.lines,{color:'#adb7b9',weight:/^(motorway|trunk)/.test(w.tags.highway)?2.5:.8,interactive:false,renderer}).addTo(base));built=true;}
 function draw(){if(!active)return;build();api.group.clearLayers();overlay.clearLayers();pins.clearLayers();leaders.clearLayers();focus.clearLayers();markers={};base.addTo(api.group);
  if(zones&&!sourceOnly)D.zones.forEach(z=>BuildingMap.shade(z.ring,{color:D.kinds[z.kind].color,weight:1,dashArray:'4 7',fillColor:D.kinds[z.kind].color,fillOpacity:.08,renderer,bubblingMouseEvents:false}).bindPopup(esc(z.title)+'<p>Authored inspection window, not a measured catchment or parcel.</p>').addTo(overlay));
  D.routes.forEach(r=>r.ways.forEach(id=>{const w=C.ways.find(w=>w.id===id);if(!w)return;L.polyline(w.lines,{color:D.kinds[r.kind].color,weight:r.kind==='steps'?6:3,dashArray:r.kind==='check'?'7 6':null,opacity:.95,renderer,bubblingMouseEvents:false}).bindPopup('<b>'+esc(r.title)+'</b><p>'+esc(r.note)+'</p><a href="https://www.openstreetmap.org/way/'+id+'" target="_blank" rel="noopener">Source way '+id+' ↗</a>').addTo(overlay);}));
  L.polygon(B.site,{color:'#253d36',weight:2.5,fillColor:'#f3de9b',fillOpacity:.85,renderer,bubblingMouseEvents:false}).on('click',()=>{if(!sourceOnly)open('P');}).addTo(overlay);overlay.addTo(api.group);
  $('ax-list').innerHTML='';tags().forEach(t=>{const k=D.kinds[t.kind];markers[t.id]=L.marker(t.at,{title:t.title,zIndexOffset:3100,bubblingMouseEvents:false,icon:L.divIcon({className:'ax-pin',html:'<button style="--ax-col:'+k.color+'" aria-label="'+esc(t.id+' '+t.title)+'">'+t.id+'</button>',iconSize:[36,29],iconAnchor:[18,14]})}).on('click',()=>open(t.id)).addTo(pins);const b=document.createElement('button');b.className='ax-item';b.dataset.axTag=t.id;b.innerHTML='<strong style="color:'+k.color+'">'+t.id+'</strong><span>'+esc(t.title)+'<small>'+esc(k.label)+'</small></span>';b.onclick=()=>open(t.id);$('ax-list').appendChild(b);});pins.addTo(api.group);leaders.addTo(api.group);focus.addTo(api.group);
  const j=D.journeys[journey];$('ax-summary').innerHTML='<h3>'+esc(sourceOnly?'Source components—not usable-route certification':j.title)+'</h3><p>'+esc(sourceOnly?'Two bridge decks, four stair ways and road components remain visible. The plot is a location reference. Local inspection tags and shading are hidden; gaps between components are not filled.':j.text)+'</p>';
  if(selected&&tags().some(t=>t.id===selected))detail(selected);else{selected=null;$('ax-detail').innerHTML='';}if(window.JuryStories)JuryStories.overview('accessibility',journey,sourceOnly);declutter();
 }
 function declutter(){if(!active)return;leaders.clearLayers();const occupied=[],offsets=[[0,0]];for(let r=1;r<=8;r++)for(let x=-r;x<=r;x++)for(let y=-r;y<=r;y++)if(Math.max(Math.abs(x),Math.abs(y))===r)offsets.push([x*44,y*36]);offsets.sort((a,b)=>a[0]*a[0]+a[1]*a[1]-b[0]*b[0]-b[1]*b[1]);tags().forEach(t=>{const marker=markers[t.id];if(!marker)return;const origin=api.map.latLngToContainerPoint(t.at);let q=origin;for(const off of offsets){const p=origin.add(off);if(!occupied.some(a=>Math.abs(a.x-p.x)<42&&Math.abs(a.y-p.y)<34)){q=p;break;}}occupied.push(q);marker.setLatLng(api.map.containerPointToLatLng(q));if(q.distanceTo(origin)>1)L.polyline([t.at,marker.getLatLng()],{color:D.kinds[t.kind].color,weight:1,dashArray:'2 3',renderer,interactive:false}).addTo(leaders);});}
 function detail(id){const t=D.tags.find(t=>t.id===id);focus.clearLayers();L.circleMarker(t.at,{radius:21,color:D.kinds[t.kind].color,fill:false,weight:2,interactive:false,renderer}).addTo(focus);$('ax-detail').innerHTML='<button id="ax-back">← All access tags</button><h3>'+esc(t.id+' · '+t.title)+'</h3><p class="ax-status">'+esc(D.kinds[t.kind].label)+' · current usability VERIFY</p><h4>Evidence</h4><p>'+esc(t.fact)+'</p><h4>What this means</h4><p>'+esc(t.meaning)+'</p><h4>Design decision to test</h4><p>'+esc(t.design)+'</p><h4>Close the gap</h4><p>'+esc(t.check)+'</p>'+(t.photo?'<figure><img loading="lazy" src="'+esc(t.photo)+'" alt="Historical Armenia bridge-angle view with railing and pavement in foreground"><figcaption>Existing screenshot · imagery April 2023 · Google Street View © Google. Historical condition, not a width measurement.</figcaption></figure>':'')+'<p class="ax-small">'+t.sources.map(s=>'<a href="'+esc(D.sources[s].url)+'" target="_blank" rel="noopener">'+esc(D.sources[s].title)+'</a>').join(' · ')+'</p>'+(t.ways?'<p class="ax-small">'+t.ways.map(id=>'<a href="https://www.openstreetmap.org/way/'+id+'" target="_blank" rel="noopener">OSM '+id+'</a>').join(' · ')+'</p>':'');if(window.JuryStories)JuryStories.detail('accessibility',id,document.getElementById('ax-detail'));$('ax-back').onclick=()=>{selected=null;$('ax-detail').innerHTML='';focus.clearLayers();};panel.querySelectorAll('[data-ax-tag]').forEach(b=>b.classList.toggle('selected',b.dataset.axTag===id));}
 function open(id){if(!tags().some(t=>t.id===id))return;selected=id;detail(id);$('ax-body').hidden=false;$('ax-collapse').setAttribute('aria-expanded','true');$('ax-collapse').textContent='−';panel.scrollTop=Math.max(0,$('ax-detail').offsetTop-panel.querySelector('header').offsetHeight-8);}
 const fields=['sidewalk','width','incline','wheelchair','kerb','tactile_paving','lit','surface'];$('ax-inventory').innerHTML='<p>'+C.ways.length+' preserved road / footway records. Number with the exact way-level tag:</p><table><thead><tr><th>Tag</th><th>Records</th></tr></thead><tbody>'+fields.map(k=>'<tr><td>'+esc(k)+'</td><td>'+C.ways.filter(w=>w.tags[k]!==undefined).length+'</td></tr>').join('')+'</tbody></table>';
 $('ax-sources').innerHTML=Object.values(D.sources).map(s=>'<p><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a><small>'+esc(s.scope)+'</small></p>').join('');
 $('ax-journey').onchange=e=>{journey=e.target.value;draw();fit();panel.scrollTop=0;};$('ax-source').onchange=e=>{sourceOnly=e.target.checked;draw();};$('ax-zones').onchange=e=>{zones=e.target.checked;draw();};$('ax-fit').onclick=fit;$('ax-plot').onclick=()=>{api.map.fitBounds(L.latLngBounds(B.site).pad(2),{...padding(),animate:false,maxZoom:19});if(!sourceOnly)open('P');};$('ax-collapse').onclick=function(){const b=$('ax-body');b.hidden=!b.hidden;this.textContent=b.hidden?'+':'−';this.setAttribute('aria-expanded',String(!b.hidden));};api.map.on('zoomend moveend',declutter);
 if(window.JuryStories)JuryStories.mount('accessibility',panel);
 return{draw,fit,open,show(on){active=on;panel.hidden=key.hidden=caption.hidden=!on;document.body.classList.toggle('accessibility-on',on);if(on){api.map.invalidateSize();draw();}},stats(){return{active,journey,sourceOnly,zones,selected,tags:Object.keys(markers),routes:D.routes.reduce((n,r)=>n+r.ways.length,0)};}};
};
