/* Independent, read-only temporal interpretation. Never writes survey/storage. */
window.createDaily=function(api){
 'use strict';
 const D=window.DAILY_DATA,B=window.PICTURES_NEW_DATA,C=window.CONNECTIONS_DATA;
 const renderer=L.canvas({padding:.35}),base=L.layerGroup(),overlay=L.layerGroup(),markers=L.layerGroup(),leaders=L.layerGroup(),focus=L.layerGroup();
 let active=false,built=false,period=3,day='weekday',event=false,evidenceOnly=false,selected=null,pins={};
 const visible={zones:true,routes:true};
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shell=document.getElementById('map').parentElement;
 const panel=document.createElement('section');panel.id='daily-panel';panel.hidden=true;panel.setAttribute('aria-label','Daily rhythm analysis');
 panel.innerHTML='<header><div><h2>Daily Rhythm</h2><small>03 / How does this area change with time?</small></div><button id="dr-collapse" aria-expanded="true" aria-label="Collapse daily rhythm panel">−</button></header>'+ 
 '<div id="dr-body"><p class="dr-status">RESEARCH + SCENARIOS · not live activity</p><div class="dr-periods" role="group" aria-label="Time of day">'+D.periods.map((p,i)=>'<button data-dr-period="'+i+'" aria-pressed="'+(i===period)+'">'+esc(p.label)+'<small>'+esc(p.hours)+'</small></button>').join('')+'</div>'+ 
 '<label class="dr-select">Compare a day type<select id="dr-day"><option value="weekday">Mon / Tue / Thu / Fri</option><option value="wednesday">Wednesday</option><option value="saturday">Saturday</option><option value="sunday">Sunday</option></select></label>'+ 
 '<div id="dr-summary" aria-live="polite"></div><p id="dr-day-note" class="dr-small"></p>'+ 
 '<label class="dr-check"><input id="dr-event" type="checkbox"> Add dated Forum event scenario</label><p class="dr-small">Royal Wedding Fair advertisement: 28 Oct–1 Nov 2026, 17–23. Separate comparison, not an event on the selected generic day or a confirmed crowd.</p>'+ 
 '<label class="dr-check"><input id="dr-evidence" type="checkbox"> Evidence only · hide local time hypotheses</label>'+ 
 '<div class="dr-actions"><button id="dr-fit">Fit study</button><button id="dr-plot">Our plot</button></div>'+ 
 '<details id="dr-key-details"><summary>What the colours and shading mean</summary><div id="dr-colours"></div><p class="dr-small">Colour changes the question being studied, NOT measured activity, density, opening status, sound level or safety. Dashed windows are analytical areas, not parcels. Question marks = VERIFY.</p><label class="dr-check"><input data-dr-layer="zones" type="checkbox" checked> Scenario windows</label><label class="dr-check"><input data-dr-layer="routes" type="checkbox" checked> Source road / approach components</label></details>'+ 
 '<div id="dr-detail" aria-live="polite"></div><div id="dr-list"></div>'+ 
 '<details id="dr-hours" open><summary>Published hours · district examples</summary><p class="dr-small">Bars show advertised opening windows, NOT people or activity levels. Examples are not transferred to nearby buildings.</p><div id="dr-schedules"></div><p class="dr-small">Jolibelle’s main section and footer conflict; no hours adopted. <a href="https://jolibellebeauty.com/" target="_blank" rel="noopener">See source ↗</a></p></details>'+ 
 '<details id="dr-findings"><summary>What this changes in the design</summary><ol><li>Separate public opening from office/workshop opening.</li><li>Protect quiet rooms and neighbours even after work closes.</li><li>Keep loading and short-stay waiting from competing.</li><li>Test the whole arrival and return route after dark.</li><li>Staff and maintain the smaller open part; do not assume 24-hour operation.</li></ol></details>'+ 
 '<details id="dr-field"><summary>Close the gaps with a repeat visit</summary><p>Use T2, T5, T6, T7 and T8 as repeat stations. Observe the same 10-minute window per station in different periods; stagger routes across visits and log actual times.</p><p>Count passing separately from stopping; log shutters, delivery obstruction, sound sources and light continuity. Repeat a weekday and weekend. Ask operators about exceptions.</p><p class="dr-small">No observations have been invented. Avoid unsafe positions; accompanied late-evening work only if appropriate. No overnight visit required.</p><a href="daily-research.html#field-plan" target="_blank" rel="noopener">Full field sheet and test criteria ↗</a></details>'+ 
 '<details id="dr-sources"><summary>Sources and geographical limits</summary><div id="dr-source-list"></div></details>'+ 
 '<p><a href="daily-research.html" target="_blank" rel="noopener">Full research, time matrix & design reasoning ↗</a></p><p class="dr-small">Times are local clock-time study bands, not sunrise/sunset or a forecast. Original survey, photos, user records and building assignments are untouched.</p></div>';
 shell.appendChild(panel);L.DomEvent.disableClickPropagation(panel);L.DomEvent.disableScrollPropagation(panel);
 const key=document.createElement('div');key.id='daily-key';key.hidden=true;shell.appendChild(key);L.DomEvent.disableClickPropagation(key);
 const caption=document.createElement('div');caption.id='daily-caption';caption.hidden=true;caption.innerHTML='↑ NORTH / UPPER · temporal hypotheses, not measured flows<br><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a> · preserved base';shell.appendChild(caption);
 const $=id=>document.getElementById(id),p=()=>D.periods[period];
 const tags=()=>D.tags.filter(t=>!evidenceOnly||t.id==='T9');
 function kind(t){if(t.id==='T9')return event?'event':'unknown';if(t.id==='P')return ['access','work','home','handover','home','rest'][period];if(['T5','T6','T7','T8'].includes(t.id))return period===5?'rest':'access';if(t.id==='T11')return period>=4?'rest':'handover';if(t.id==='T4')return D.zones[2].kinds[period];if(t.id==='T2')return D.zones[1].kinds[period];return D.zones[0].kinds[period];}
 function eventState(){if(!event)return 'Daily opening / attendance unknown';return period===3?'Advertised opening at 17:00 within this band':period===4?'Advertised event window 18:00–21:00':period===5?'Advertised until 23:00; later conditions TBD':'Outside advertised visitor hours; setup/access TBD';}
 function state(t){return t.id==='T9'?eventState():t.states[period];}
 function pad(){return innerWidth<700?{paddingTopLeft:[38,55],paddingBottomRight:[22,panel.offsetHeight+20]}:{paddingTopLeft:[70,70],paddingBottomRight:[panel.offsetWidth+42,70]};}
 function fit(){api.map.invalidateSize();api.map.fitBounds(B.bounds,{...pad(),animate:false});}
 function build(){if(built)return;B.base.forEach(f=>{if(f.building)return;if(f.polygon)L.polygon(f.polygon,{stroke:false,fillColor:f.color==='#2469b9'?'#c4dbe6':'#e4e9e3',fillOpacity:1,interactive:false,renderer}).addTo(base);});B.buildings.forEach(b=>L.polygon(b.rings,{color:'#899496',weight:.7,fill:false,opacity:.65,interactive:false,renderer}).addTo(base));C.ways.forEach(w=>L.polyline(w.lines,{color:'#acb6b8',weight:/^(motorway|trunk)/.test(w.tags.highway)?2:1,opacity:.65,interactive:false,renderer}).addTo(base));built=true;}
 function draw(){
  if(!active)return;build();api.group.clearLayers();overlay.clearLayers();markers.clearLayers();leaders.clearLayers();focus.clearLayers();pins={};base.addTo(api.group);
  if(visible.zones&&!evidenceOnly)D.zones.forEach(z=>{const col=D.kinds[z.kinds[period]].color;L.polygon(z.ring,{color:col,weight:1,dashArray:'5 8',fillColor:col,fillOpacity:.12,interactive:false,renderer}).addTo(overlay);L.marker(z.at,{interactive:false,keyboard:false,icon:L.divIcon({className:'dr-area',html:'<b>'+esc(z.title)+'</b><span>'+esc(z.states[period])+'</span>',iconSize:[230,42],iconAnchor:[115,21]})}).addTo(markers);});
  if(visible.routes)D.routes.forEach(r=>r.ways.forEach(id=>{const w=C.ways.find(w=>w.id===id);if(w)L.polyline(w.lines,{color:r.id==='highway'?'#59666d':'#347da0',weight:r.id==='highway'?3.5:3,dashArray:r.id==='highway'?null:'7 5',opacity:.9,renderer,bubblingMouseEvents:false}).bindPopup('<b>'+esc(r.title)+'</b><p>Geometry only: no hourly flow, lighting or access status assigned.</p><a href="https://www.openstreetmap.org/way/'+id+'" target="_blank" rel="noopener">OSM way '+id+'</a>').addTo(overlay);}));
  L.polygon(B.site,{color:'#283d39',weight:2.5,fillColor:'#f7db8b',fillOpacity:.9,renderer,bubblingMouseEvents:false}).on('click',()=>{if(!evidenceOnly)open('P');}).addTo(overlay);overlay.addTo(api.group);
  if(event)L.circleMarker(D.tags.find(t=>t.id==='T9').at,{radius:27,color:D.kinds.event.color,weight:1,dashArray:'4 4',fillOpacity:.08,renderer,interactive:false}).addTo(overlay);
  $('dr-list').innerHTML='';tags().forEach(t=>{const col=D.kinds[kind(t)].color;pins[t.id]=L.marker(t.at,{icon:L.divIcon({className:'dr-pin',html:'<button style="--dr-colour:'+col+'" aria-label="'+esc(t.id+' '+t.title)+'">'+t.id+'</button>',iconSize:[36,29],iconAnchor:[18,14]}),title:t.title,zIndexOffset:3100,bubblingMouseEvents:false}).on('click',()=>open(t.id)).addTo(markers);const b=document.createElement('button');b.className='dr-item';b.dataset.drTag=t.id;b.innerHTML='<strong style="color:'+col+'">'+t.id+'</strong><span>'+esc(t.title)+'<small>'+esc(state(t))+'</small></span>';b.onclick=()=>open(t.id);$('dr-list').appendChild(b);});markers.addTo(api.group);leaders.addTo(api.group);focus.addTo(api.group);
  $('dr-summary').innerHTML=evidenceOnly?'<h3>Evidence at '+esc(p().hours)+'</h3><p>Published district schedules are below. Local hourly activity, comfort and access observations are not yet available; local temporal scenarios are hidden.</p>':'<h3>'+esc(p().title)+'</h3><p>'+esc(p().lead)+'</p><div class="dr-takeaway"><b>AT OUR PLOT</b><p>'+esc(p().plot)+'</p></div>';
  $('dr-day-note').textContent=evidenceOnly?'Day selection compares advertised hours only. Exact-site activity and current operation remain unverified.':D.dayNotes[day];
  key.innerHTML='<b>'+esc(p().hours)+' / '+esc(p().label.toUpperCase())+'</b><span>'+(evidenceOnly?'Evidence-only view: local scenarios hidden':'Shading = changing question, not intensity')+'</span>'+Object.entries(D.kinds).filter(([id])=>id!=='event'||event).map(([id,k])=>'<span><i style="background:'+k.color+'"></i>'+esc(k.label)+'</span>').join('')+'<small>12 research tags · click for evidence → implication<br>Dashed pointers connect displaced labels only.</small>';
  if(evidenceOnly)key.innerHTML='<b>EVIDENCE ONLY</b><span>Source geometry + Forum context</span><small>Local time-of-day hypotheses hidden.<br>District published hours remain in the panel.<br>No observed temporal counts available.</small>';
  schedules();if(selected&&tags().some(t=>t.id===selected))detail(selected);else{selected=null;$('dr-detail').innerHTML='';}declutter();
 }
 function declutter(){if(!active)return;leaders.clearLayers();const occupied=[];tags().forEach(t=>{const pin=pins[t.id];if(!pin)return;const o=api.map.latLngToContainerPoint(t.at);let q=o;const offsets=[[0,0],[44,-30],[-44,30],[44,30],[-44,-30],[0,52],[0,-52],[72,0],[-72,0],[80,-45],[-80,45]];for(const off of offsets){const test=o.add(off);if(!occupied.some(a=>Math.abs(a.x-test.x)<43&&Math.abs(a.y-test.y)<34)){q=test;break;}}occupied.push(q);pin.setLatLng(api.map.containerPointToLatLng(q));if(q.distanceTo(o)>1)L.polyline([t.at,pin.getLatLng()],{color:D.kinds[kind(t)].color,weight:1,dashArray:'2 3',interactive:false,renderer}).addTo(leaders);});}
 function detail(id){const t=D.tags.find(t=>t.id===id);if(!t)return;focus.clearLayers();L.circleMarker(t.at,{radius:22,color:D.kinds[kind(t)].color,weight:2,fill:false,interactive:false,renderer}).addTo(focus);$('dr-detail').innerHTML='<button id="dr-back">← All time tags</button><h3>'+esc(t.id+' · '+t.title)+'</h3><p class="dr-status">'+(t.id==='T9'?'Dated operator evidence / no attendance counts':'Local time interpretation · VERIFY')+'</p><h4>This period · '+esc(p().hours)+'</h4><p>'+esc(state(t))+'</p><h4>Evidence underneath</h4><p>'+esc(t.fact)+'</p><h4>Design consequence to test</h4><p>'+esc(t.design)+'</p><h4>What to check</h4><p>'+esc(t.test)+'</p><p class="dr-small">'+t.sources.map(id=>'<a href="'+esc(D.sources[id].url)+'" target="_blank" rel="noopener">'+esc(D.sources[id].title)+'</a>').join(' · ')+'</p>';$('dr-back').onclick=()=>{selected=null;$('dr-detail').innerHTML='';focus.clearLayers();};panel.querySelectorAll('[data-dr-tag]').forEach(b=>b.classList.toggle('selected',b.dataset.drTag===id));}
 function open(id){if(!tags().some(t=>t.id===id))return;selected=id;detail(id);$('dr-body').hidden=false;$('dr-collapse').setAttribute('aria-expanded','true');$('dr-collapse').textContent='−';panel.scrollTop=Math.max(0,$('dr-detail').offsetTop-panel.querySelector('header').offsetHeight-8);}
 function clock(h){return String(Math.floor(h)).padStart(2,'0')+':'+String(Math.round((h%1)*60)).padStart(2,'0');}
 function status(ranges){const windows=p().end>24?[[p().start,24],[0,p().end-24]]:[[p().start,p().end]];const total=windows.reduce((n,[a,b])=>n+b-a,0);let overlap=0;for(const [a,b]of windows)for(const [c,d]of ranges)overlap+=Math.max(0,Math.min(b,d)-Math.max(a,c));return !ranges.length?'Published closed on this day':overlap===0?'Outside published window':overlap===total?'Published window covers this band':'Published window covers part of this band';}
 function schedules(){ $('dr-schedules').innerHTML=D.schedules.map(s=>{const ranges=s.byDay[day];return '<article class="dr-schedule"><b>'+esc(s.name)+'</b><small>'+esc(s.where)+'</small><p>'+esc(ranges.length?ranges.map(([a,b])=>clock(a)+'–'+clock(b)).join(', '):'Closed')+'</p><div class="dr-bar" aria-label="Published hours '+esc(ranges.map(([a,b])=>clock(a)+' to '+clock(b)).join(', ')||'closed')+'">'+ranges.map(([a,b])=>'<i style="left:'+(a/24*100)+'%;width:'+((b-a)/24*100)+'%"></i>').join('')+'</div><div class="dr-ticks"><span>00</span><span>06</span><span>12</span><span>18</span><span>24</span></div><p class="dr-overlap">'+esc(status(ranges))+'</p><small>'+esc(s.note)+' <a href="'+esc(D.sources[s.source].url)+'" target="_blank" rel="noopener">Source ↗</a></small></article>';}).join('');}
 $('dr-colours').innerHTML=Object.values(D.kinds).map(k=>'<p class="dr-colour"><i style="background:'+k.color+'"></i>'+esc(k.label)+'</p>').join('');
 $('dr-source-list').innerHTML=Object.values(D.sources).map(s=>'<p><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a><small>'+esc(s.date)+'</small><small>'+esc(s.scope)+'</small></p>').join('');
 panel.querySelectorAll('[data-dr-period]').forEach(b=>b.onclick=()=>{period=Number(b.dataset.drPeriod);panel.querySelectorAll('[data-dr-period]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();panel.scrollTop=0;});
 $('dr-day').onchange=e=>{day=e.target.value;draw();};$('dr-event').onchange=e=>{event=e.target.checked;draw();};$('dr-evidence').onchange=e=>{evidenceOnly=e.target.checked;draw();};
 panel.querySelectorAll('[data-dr-layer]').forEach(c=>c.onchange=()=>{visible[c.dataset.drLayer]=c.checked;draw();});
 $('dr-fit').onclick=fit;$('dr-plot').onclick=()=>{api.map.fitBounds(L.latLngBounds(B.site).pad(2),{...pad(),animate:false,maxZoom:19});if(!evidenceOnly)open('P');};
 $('dr-collapse').onclick=function(){const b=$('dr-body');b.hidden=!b.hidden;this.setAttribute('aria-expanded',String(!b.hidden));this.textContent=b.hidden?'+':'−';};api.map.on('zoomend moveend',declutter);
 return {draw,fit,open,show(on){active=on;panel.hidden=key.hidden=caption.hidden=!on;document.body.classList.toggle('daily-on',on);if(on){api.map.invalidateSize();draw();}},stats(){return{active,period:p().id,day,event,evidenceOnly,selected,tags:Object.keys(pins),layers:{...visible}};}};
};
