/* Authored temporal study, 2026-09-14. No measured flows, inferred business hours or survey writes. */
window.DAILY_DATA = {
 version:'2026-09-14-1',
 sources:{
  local:{title:'Preserved site geometry and use records',url:'daily-research.html#local-evidence',date:'Project copy, 2026-09-14',scope:'OSM extract 2026-09-13; original use fields and approximate placements. Not time-series observations.'},
  brief:{title:'Official studio programme',url:'daily-research.html#design',date:'Fall 2026',scope:'Existing programme categories, not approved opening hours or a demand survey.'},
  aub:{title:'AUB / Dagher & Samaha · Rethinking Shared Space',url:'https://www.aub.edu.lb/ifi/Documents/publications/working_papers/2015-2016/20160822_nabaa.pdf',date:'October 2016; printed pp.10,13,15',scope:'Historical fieldwork on Sis Street, Nabaa. Different subarea; no timetable transferred to our plot.'},
  sound:{title:'The Public Source · Sound and the Fury',url:'https://thepublicsource.org/photo-essays/sound-and-fury-living-noise-pollution-beirut',date:'27 March 2024; photographs 4 July 2022',scope:'Firsthand accounts across Dawra/Bourj Hammoud and other neighbourhoods. Not measured sound at this plot.'},
  lights:{title:'UN-Habitat · Maraach alleyway improvements',url:'https://unhabitat.org/news/09-nov-2022/urban-october-in-beirut-improving-life-through-urban-interventions',date:'9 November 2022; article dateline 7 November',scope:'Five alleyways in Maraach, not our bridge or plot. Historical intervention and resident testimony.'},
  saro:{title:'Crochet Saro · Arax Street store hours',url:'https://crochetsaro.com/pages/our-story',date:'Undated operator page; checked 2026-09-14',scope:'Two Arax Street stores only. Off-map district example, not all retail.'},
  unigaz:{title:'Unigaz · Shell Street / Seaside Road',url:'https://unigazstore.com/',date:'Undated operator storefront; checked 2026-09-14',scope:'One service operator. Exact building not assigned in this map; not an industrial-shift schedule.'},
  forum:{title:'Forum de Beyrouth · advertised events',url:'https://forum.ws/',date:'Checked 2026-09-14; future event listings',scope:'Royal Wedding Fair, 28 Oct–1 Nov 2026, 17:00–23:00. Advertised, not verified attendance or occurrence.'},
  isf:{title:'ISF · dated coastal traffic measures',url:'https://isf.gov.lb/news/traffic-measures-along-the-coastal-road-in-dbayeh-on-28-06-2026-on-the-occasion-of-a-running-race/',date:'27 June 2026 notice for 28 June 2026',scope:'Historical event-specific changes near Forum/Emile Lahoud. Not an ordinary Sunday condition.'},
  yfc:{title:'YFC Lebanon · Manara Youth Center',url:'https://yfclebanon.org/manara-youth-center/',date:'Undated provider page; checked 2026-09-14',scope:'After-school and summer programmes; no exact timetable adopted. District context, no origin pin.'},
  conflict:{title:'Jolibelle · conflicting published hours',url:'https://jolibellebeauty.com/',date:'Checked 2026-09-14',scope:'Main hours and footer disagree. Excluded from the schedule comparison until confirmed.'}
 },
 periods:[
  {id:'early',label:'Early',hours:'05–08',start:5,end:8,title:'Before the workday',lead:'Test opening, deliveries and early journeys separately. An empty-looking photograph cannot establish an empty morning.',plot:'A clear arrival and service arrangement may matter before exhibition or office hours. Do not open every part of the building by default.',observe:'Record first openings, delivery stops and people passing versus waiting. No local morning peak has been measured.'},
  {id:'work',label:'Morning',hours:'08–12',start:8,end:12,title:'Work and movement overlap',lead:'The mapped mix of homes, shops and workshops suggests overlapping activities—not a purely industrial north and residential south.',plot:'Test a short-stay welcome for nearby workers alongside controlled work/learning rooms; keep carrying and loading out of the waiting space.',observe:'Compare the plot-side lane, bridge landing and nearby working frontage during the same sampling window.'},
  {id:'midday',label:'Midday',hours:'12–15',start:12,end:15,title:'Passing through versus staying',lead:'A route can carry people without offering somewhere comfortable to stop. Breaks, deliveries and outdoor comfort need separate checks.',plot:'Test a sheltered pause near the entrance. Do not infer lunchtime demand, shade, cooling or quiet from the plan alone.',observe:'Log stationary people, shaded/unshaded positions, open doors and intermittent sound. Do not assume every worker takes the same break.'},
  {id:'handover',label:'Afternoon',hours:'15–18',start:15,end:18,title:'The handover to investigate',lead:'Work, shopping, learning and home routines may overlap rather than change at one closing time. This is the most useful transition to test.',plot:'Can a shared learning/exhibition room remain available while offices begin to close? Check staffing, toilets and an independent access boundary.',observe:'Return to the same frontages: note shutters, returning trips, deliveries and who actually stops. School finish times remain TBD.'},
  {id:'evening',label:'Evening',hours:'18–21',start:18,end:21,title:'Less work does not mean less life',lead:'Some published services extend into the evening; nearby residential uses remain relevant. The actual amount of street activity is unknown.',plot:'A smaller, visible public zone could work without opening the whole hub. Shelter should not create a concealed, unstaffed entrance.',observe:'Check continuity of light and access from both directions; record whether shop lighting disappears when shutters close.'},
  {id:'night',label:'Night',hours:'21–05',start:21,end:29,title:'Rest, late arrivals and residual noise',lead:'Do not equate closed shops with silence or assume an all-night audience. Traffic, plant, events and homes have different clocks.',plot:'Protect the quiet interior and neighbours; test controlled closing, clear exit routes and quiet servicing. A 24-hour hub is not assumed.',observe:'A short, accompanied late-evening check is enough to start. Overnight conditions stay unknown unless safely observed; never extrapolate a 22:00 visit to 04:00.'}
 ],
 kinds:{work:{color:'#b37929',label:'Work / commerce question'},home:{color:'#31816a',label:'Home / everyday use question'},access:{color:'#347da0',label:'Movement / access check'},handover:{color:'#b14e69',label:'Overlap / handover question'},rest:{color:'#765d9c',label:'Rest / lighting check'},unknown:{color:'#858e92',label:'Timing unknown'},event:{color:'#a85391',label:'Dated event only'}},
 zones:[
  {id:'south',title:'SOUTH · mixed neighbourhood',at:[33.89295,35.5425],ring:[[33.89605,35.5377],[33.8948,35.5426],[33.8935,35.5481],[33.8912,35.5481],[33.8912,35.5361],[33.8941,35.5371]],kinds:['home','work','home','handover','home','rest'],states:['Early home / work journeys?','Homes + ground-floor work','Breaks and everyday errands?','Returning + continuing work?','Home routines / some commerce?','Residential rest; street use TBD']},
  {id:'near',title:'PLOT SIDE · working frontages',at:[33.89708,35.5437],ring:[[33.89815,35.5386],[33.89772,35.542],[33.8958,35.5481],[33.89485,35.5481],[33.89615,35.5414],[33.89665,35.5384]],kinds:['work','work','work','handover','unknown','rest'],states:['Opening and deliveries?','Work / customers / loading?','Short breaks + servicing?','Staggered closing?','Which doors remain active?','Closed frontage ≠ silence']},
  {id:'north',title:'NORTH · production + mixed uses',at:[33.9003,35.5444],ring:[[33.89885,35.5396],[33.90165,35.5405],[33.90165,35.5481],[33.89665,35.5481],[33.8978,35.5421]],kinds:['unknown','work','work','handover','unknown','unknown'],states:['Shifts / gate hours unknown','Business hours vary','Do not assume common breaks','Some activity may continue','Not a blanket closure zone','No shift or occupancy data']},
  {id:'west',title:'WEST · cross-river context',at:[33.9001,35.5359],ring:[[33.9016,35.5347],[33.9016,35.5382],[33.8984,35.5368],[33.8955,35.5352],[33.8955,35.5347]],kinds:['access','access','access','access','access','rest'],states:['Cross-river journey check','Passing ≠ visiting the plot','Crossing + onward route TBD','Arrival / return route test','Event scenario is separate','Return route / light TBD']}
 ],
 routes:[
  {id:'highway',kind:'access',ways:[237737315,200611932,692409629],title:'Main highway · clock-specific traffic and sound TBD'},
  {id:'approach',kind:'access',ways:[306996681,715531021,701135687,701135688,270786366,275315121],title:'Street 52 → bridge/stairs → Street 80 · candidate components, not a verified journey'},
  {id:'river',kind:'access',ways:[452148075,452148076],title:'Armenia road bridge · onward journey and after-dark conditions TBD'}
 ],
 tags:[
  {id:'P',at:[33.89654,35.54112],title:'Our plot · one hub, different opening layers',sources:['local','brief'],fact:'The plot adjoins the main highway and plot-side street; the brief combines public, work, cultural, learning and productive functions.',states:['Arrival before full opening','Work + public welcome','Sheltered short stay','Separate public / work clocks','Small public zone can stay open?','Quiet close-down, not 24/7 by default'],design:'Test independently controlled public, quiet-work and service zones. This develops nesting as timed access and environmental separation, not simply boxes inside boxes.',test:'Ask potential users about actual available times; test staffing, operating cost, supervision, accessible entry and escape in each mode.'},
  {id:'T1',at:[33.89482,35.54035],title:'Southern homes + ground-floor trade',sources:['local','sound'],fact:'Preserved mixed-use records south of the highway include shops and workshops. A closed ground floor does not establish that the upper floors are empty.',states:['Early journeys?','Home + work overlap','Who can stop here?','Returns + shops still working?','Home routines / retail varies','Rest remains relevant'],design:'Do not place late noisy events or unloading beside residential interfaces simply because shops are closed.',test:'At the same street segment, log entrances, shutters and stationary activity in every period; dwelling occupancy and footfall remain unknown.'},
  {id:'T2',at:[33.89715,35.54186],title:'Immediate workshop / service frontages',sources:['local','sound','aub'],fact:'Original records 145 and 149 document workshop-related ground uses. Their operating hours and current status are not established.',states:['Opening / loading check','Work / customer interface','Deliveries can still occur','Closing is not simultaneous','Late work is possible, not assumed','Do not forecast silence'],design:'Separate public waiting and material handling. A closing workshop may change local sound without eliminating highway or plant sources.',test:'Record source start/stop times and blocking deliveries, not only total traffic. Obtain each operator’s actual schedule if willing.'},
  {id:'T3',at:[33.89857,35.54108],title:'Northern mixed block · homes also here',sources:['local'],fact:'Original records 97/109 have mixed workshop uses and 105 is residential. Northern activity cannot be reduced to a single office shift.',states:['Residents / workers differ','Mixed clocks in one block','Breaks vary by user','Different closing times?','Homes do not close with offices','Street presence unknown'],design:'Give the northern approach the same attention to quiet rooms, legibility and welcoming access as the southern approach.',test:'Confirm uses and entrance positions before inferring where people will come from or when they will attend.'},
  {id:'T4',at:[33.89945,35.54485],title:'Northern business / production study window',sources:['local','unigaz'],fact:'The larger northern context contains business and production activity. The Unigaz operator schedule is a separate district example, not the hours of this tag.',states:['Shift starts TBD','Work activity hypothesis','No shared lunch hour assumed','Departure / delivery overlap?','Some services may continue','Shift work remains TBD'],design:'Do not size or schedule the hub around an invented universal 09–17 workday.',test:'Verify operator gates, shifts and visitor access. No workers, factories or exact hours are assigned to this analytical point.'},
  {id:'T5',at:[33.89566,35.54355],title:'Highway · a different clock',sources:['local','sound'],fact:'The highway remains a physical edge regardless of nearby shop hours. Local hourly flow, speed and sound have not been measured.',states:['Traffic level TBD','No verified rush-hour curve','Passing traffic ≠ hub users','Test overlap with local return trips','Do not infer quiet from shutters','Residual sound / peaks TBD'],design:'Keep protection for quiet activities across operating modes; avoid relying on workshop closure for acoustic comfort.',test:'At a fixed safe receiver position record traffic and sound separately in each period; no invented decibel contours or attenuation values.'},
  {id:'T6',at:[33.89604,35.54092],title:'C1 footbridge · same geometry, changing conditions',sources:['local','lights'],fact:'OSM maps a footbridge and stairs near the plot. Lighting, step-free continuity and actual pedestrian demand are unverified.',states:['Early access / visibility check','Workday crossing check','Exposure while waiting?','Passing versus gathering?','Light continuity check','Return route check'],design:'A well-lit project door is insufficient if the preceding landing and street transition fail. The project cannot claim to repair the full route alone.',test:'Observe both landings and onward links. Ask about access difficulties; do not label the route safe, unsafe or accessible from aerial geometry.'},
  {id:'T7',at:[33.89738,35.54159],title:'Street 80 · walking and servicing at one edge',sources:['local','aub'],fact:'The mapped plot-side street is a candidate approach component. No local delivery timetable or clear-width survey exists.',states:['Possible loading / arrival overlap','Customer / vehicle interface','Unscheduled delivery test','Departure / arrival overlap','Which doors and lights remain?','Late service / closing check'],design:'Test separate waiting and loading areas, and agree service windows only after observing actual conflicts.',test:'Log the obstruction duration and remaining walking space. Do not assume all deliveries finish before visitors arrive.'},
  {id:'T8',at:[33.8954,35.53678],title:'Armenia bridge · onward trip, not a shortcut',sources:['local'],fact:'The mapped road bridge crosses the river. This does not establish a continuous comfortable walk from western destinations to the plot.',states:['Early trip conditions TBD','Pedestrian / vehicle separation?','Distance and effort matter','Journey home as well as arrival','After-dark onward links TBD','No automatic event spillover'],design:'Keep cross-river visitors conditional. Do not open a late programme assuming nearby event attendance will walk here.',test:'Follow only safe public paths and record actual route changes, crossings and travel time. No direct line over the river is a route.'},
  {id:'T9',at:[33.89762,35.53538],title:'Forum · a dated event clock',sources:['forum','isf','local'],fact:'Venue location is established in the source map; the event scenario uses the operator’s dated advertisement, not a daily opening schedule.',states:['No daily hours inferred','No daily hours inferred','No daily hours inferred','Event scenario: opening may fall here','Event scenario: advertised window','Event scenario: evening may extend here'],design:'Test occasional arrival, waiting and return arrangements without making event spillover the hub’s everyday demand case.',test:'Recheck the event and count actual pedestrian directions on an event day and a comparable non-event day. Published hours do not measure attendance.'},
  {id:'T10',at:[33.89375,35.54435],title:'Local learning · timing must match availability',sources:['local','yfc'],fact:'A district provider describes after-school and summer activities. It does not establish demand or a timetable for this block or the new project.',states:['Early availability unknown','Work / school constraints?','Do not assume free time','After-school is a category, not a bell time','Short sessions to test','No all-night learning claim'],design:'Test bookable rooms and short sessions independently of office access; coordinate with existing provision rather than duplicating it.',test:'Ask users and providers about days, finish times, fees and seasonal changes. No school gate or child flow is mapped here.'},
  {id:'T11',at:[33.89689,35.54086],title:'Plot threshold · sun, light and shelter change',sources:['local','lights'],fact:'The open plot is next to transport infrastructure. This layer has no checked shadow model, lux survey or outdoor comfort measurements.',states:['Daylight depends on date','Moving sun / shade to test','Unshaded pause may be difficult','Shadows and activity can shift','18:00 is not always after dark','Artificial light / glare check'],design:'Combine weather protection with a visible entrance and a quieter place to pause. A bright facade alone does not prove a usable approach.',test:'Use Sun/Wind analysis separately; sample sun/shade and lighting on dated visits. These time bands are not sunrise/sunset boundaries.'}
 ],
 schedules:[
  {id:'saro',name:'Crochet Saro · Arax Street',where:'Off-map district example; not a tagged building',source:'saro',byDay:{weekday:[[9.5,19]],wednesday:[[9.5,19]],saturday:[[9.5,19]],sunday:[]},note:'Operator-published hours; current operation VERIFY.'},
  {id:'unigaz',name:'Unigaz · Shell Street / Seaside Road',where:'District service example; exact footprint not assigned',source:'unigaz',byDay:{weekday:[[8.5,20+40/60]],wednesday:[[8.5,14]],saturday:[[8.5,20+40/60]],sunday:[[12,20+40/60]]},note:'One service, not all northern businesses. Current operation VERIFY.'}
 ],
 dayNotes:{weekday:'Mon / Tue / Thu / Fri comparison. This is an ordinary-day hypothesis, not a measured workday. Exact shifts, school hours and traffic peaks remain TBD.',wednesday:'A midweek exception matters: one published service schedule ends earlier. Other businesses are not assumed to follow it.',saturday:'Retail and services may still operate. Do not copy a weekday commuter or school pattern onto Saturday; observe it separately.',sunday:'Closure and continued service coexist in the examples below. Residents, visits and deliveries do not disappear; neighbourhood activity remains unmeasured.'}
};
