/* Standalone analytical layer. Only reads existing data; never changes survey/storage. */
window.createPeople=function(api){
 'use strict';
 const D=window.PEOPLE_DATA,B=window.PICTURES_NEW_DATA,C=window.CONNECTIONS_DATA,A=window.PICTURES_AUTO_ADDITIONS;
 const colors={south:'#307c67',near:'#b16c32',north:'#7153a1',west:'#367f9c',access:'#b54159',plot:'#263d39'};
 const canvas=L.canvas({padding:.35}),base=L.layerGroup(),overlay=L.layerGroup(),markers=L.layerGroup(),leaders=L.layerGroup(),focus=L.layerGroup();
 let active=false,built=false,mode='all',selected=null,pins={};
 const visible={zones:true,routes:true,evidence:false};
 const shell=document.getElementById('map').parentElement;
 const panel=document.createElement('section');panel.id='people-panel';panel.hidden=true;panel.setAttribute('aria-label','People and needs analysis');
 panel.innerHTML='<header><div><h2>People & Needs</h2><small>02 / Potential users · not measured demand</small></div><button id="ppl-collapse" aria-label="Collapse people panel" aria-expanded="true">−</button></header>'+
 '<div id="ppl-body"><p class="ppl-lead">Who would come—and what would make them return?</p><p class="ppl-sub">Start with nearby people, then test specialised visitors. Upper = north; lower = south. These areas overlap in use.</p>'+
 '<div class="ppl-presets" role="group" aria-label="User origins"><button data-origin="all" aria-pressed="true">All origins</button><button data-origin="south" aria-pressed="false">South / lower</button><button data-origin="north" aria-pressed="false">North / upper</button><button data-origin="west" aria-pressed="false">Across river</button></div>'+
 '<div class="ppl-actions"><button id="ppl-fit">Fit this view</button><button id="ppl-plot">Our plot</button></div>'+
 '<details id="ppl-layers"><summary>Map key & layers</summary><label><input type="checkbox" data-ppl-layer="zones" checked> Building-aligned origin-study tint</label><label><input type="checkbox" data-ppl-layer="routes" checked> Approach components to test</label><label><input type="checkbox" data-ppl-layer="evidence"> Selected original use records</label><p class="ppl-small">Shading is an interpretative window, not population density or a fixed catchment. Dashed routes follow mapped road/bridge components but are not verified journeys. Small dotted pointers connect labels only. ≈ means approximate. No predicted flow volumes.</p></details>'+
 '<div id="ppl-detail" aria-live="polite"></div><div id="ppl-list"></div>'+
 '<details id="ppl-priority"><summary>Which users come first?</summary><p><b>First to investigate:</b> nearby residents, workshop/shop users and learners. They have the strongest local-context relationship, but their unmet needs are not yet confirmed.</p><p><b>Secondary:</b> creative/business collaborators and visitors coming for a specific activity.</p><p><b>Not yet a demand case:</b> highway traffic, waterfront workers and automatic spillover from Forum events.</p></details>'+
 '<details id="ppl-day"><summary>A day to test—not an observed timetable</summary><dl><dt>Before / during work</dt><dd>Short breaks, booked meetings and practical support.</dd><dt>After school / after work</dt><dd>Learning sessions, shared work and local meetings.</dd><dt>Evenings / weekends</dt><dd>Scheduled exhibitions, demonstrations and community events.</dd></dl><p class="ppl-small">Ask each group about availability. Do not assume these rhythms, combine unrelated peaks, or infer opening hours.</p></details>'+
 '<details id="ppl-design"><summary>What this asks the building to do</summary><ol><li>A reachable welcome and sheltered pause, without a compulsory purchase.</li><li>Learning + making linked to display and small meetings.</li><li>Quiet work separated from demonstration noise and deliveries.</li><li>Rooms that can open at different times without opening every floor.</li><li>Accessible arrival—not only an internal lift.</li></ol><p class="ppl-small">Design hypotheses within the brief, not approved programme changes. Nesting must protect these activities without hiding them from arrivals.</p></details>'+
 '<details id="ppl-sources"><summary>Sources & limits</summary><div id="ppl-source-list"></div></details>'+
 '<p><a href="people-research.html" target="_blank" rel="noopener">Full analysis, programme fit & verification plan ↗</a></p><p class="ppl-small">No interviews or origin–destination counts yet. Existing survey and photos are unchanged. Waterfront and several district organisations lie beyond this map.</p></div>';
 shell.appendChild(panel);L.DomEvent.disableClickPropagation(panel);L.DomEvent.disableScrollPropagation(panel);
 const key=document.createElement('div');key.id='people-key';key.hidden=true;key.innerHTML='<b>PEOPLE / 02</b>'+[['south','South · residents + trade'],['near','Nearby · working frontages'],['north','North · business + mixed uses'],['west','West · conditional visitors'],['access','Crossing · access test']].map(([c,t])=>'<span><i style="background:'+colors[c]+'"></i>'+t+'</span>').join('')+'<small>Colour = study context, NOT a person’s identity.<br>Building tint ≠ recorded use or density · routes ≠ counted flows</small>';shell.appendChild(key);L.DomEvent.disableClickPropagation(key);
 const caption=document.createElement('div');caption.id='people-caption';caption.hidden=true;caption.innerHTML='<b>↑ NORTH / UPPER</b> · origins are hypotheses, not traced journeys<br><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a> · corrected building base · tint = context, not recorded use';shell.appendChild(caption);
 const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const allowed=t=>mode==='all'||t.area==='plot'||t.area==='access'||(mode==='north'?['north','near'].includes(t.area):t.area===mode);
 const zoneAllowed=z=>mode==='all'||(mode==='north'?['north','near'].includes(z.id):z.id===mode);
 function pad(){return innerWidth<700?{paddingTopLeft:[35,55],paddingBottomRight:[20,panel.offsetHeight+18]}:{paddingTopLeft:[65,65],paddingBottomRight:[panel.offsetWidth+42,75]};}
 function fit(){const b={all:B.bounds,south:[[33.8913,35.5368],[33.8971,35.5452]],north:[[33.8961,35.5382],[33.9016,35.5464]],west:[[33.8947,35.5347],[33.9003,35.542]]};api.map.invalidateSize();api.map.fitBounds(b[mode],{...pad(),animate:false});}
 function build(){if(window.BuildingMap){BuildingMap.base(base,canvas);return;}if(built)return;B.base.forEach(f=>{if(f.building)return;if(f.polygon)L.polygon(f.polygon,{stroke:false,fillColor:f.color==='#2469b9'?'#c2d8e1':'#e3e5e0',fillOpacity:1,interactive:false,renderer:canvas}).addTo(base);});B.buildings.forEach(b=>L.polygon(b.rings,{color:'#78878c',weight:.65,fill:false,opacity:.7,interactive:false,renderer:canvas}).addTo(base));C.ways.forEach(w=>L.polyline(w.lines,{color:/^(motorway|trunk)/.test(w.tags.highway)?'#a2aaa7':'#b9c2be',weight:/^(motorway|trunk)/.test(w.tags.highway)?2:1,opacity:.65,interactive:false,renderer:canvas}).addTo(base));built=true;}
 function draw(){
  if(!active)return;build();api.group.clearLayers();overlay.clearLayers();markers.clearLayers();leaders.clearLayers();focus.clearLayers();pins={};base.addTo(api.group);
  if(visible.zones)D.zones.filter(zoneAllowed).forEach(z=>{BuildingMap.shade(z.ring,{color:z.color,weight:1,dashArray:'5 8',fillColor:z.color,fillOpacity:.13,renderer:canvas}).bindPopup('<b>'+esc(z.title)+'</b><p>Interpretative origin-study window. Not a surveyed district, population density, exclusive user group or measured catchment.</p>').addTo(overlay);L.marker(z.at,{interactive:false,keyboard:false,icon:L.divIcon({className:'ppl-area',html:esc(z.title),iconSize:[225,35],iconAnchor:[112,18]})}).addTo(markers);});
  if(visible.routes)D.routes.filter(r=>mode==='all'||r.id===mode).forEach(r=>r.ways.forEach(id=>{const w=C.ways.find(w=>w.id===id);if(w)L.polyline(w.lines,{color:r.color,weight:4,dashArray:'8 5',opacity:.95,renderer:canvas,bubblingMouseEvents:false}).bindPopup('<b>'+esc(r.title)+'</b><p>'+esc(r.note)+'</p><a href="https://www.openstreetmap.org/way/'+id+'" target="_blank" rel="noopener">OSM way '+id+'</a>').addTo(overlay);}));
  if(visible.evidence){const ids=['wmttorinikfw','wmttot59lzkm','wmttowqfujyr','wmttqqhnabe0','wmtusunqdx74','wmtut5sbvaw1','wmtut2lhb594','wmtuto6tyn0b'];ids.forEach(id=>{const r=A.records.find(r=>r.id===id),p=A.layout.placements[id]||B.seeds[id];if(!r||!p?.anchor)return;L.circleMarker(p.anchor,{radius:5,color:'#253d39',weight:1.5,fillColor:'#fff',fillOpacity:1,renderer:canvas,bubblingMouseEvents:false}).bindPopup('<b>Original record '+esc(r.parcel)+'</b><p>Recorded use: '+esc(r.use||'TBD')+'<br>Ground: '+esc(r.ground||'TBD')+'</p><p>Existing recorded observation; provisional map placement. Not a current occupant count or confirmed need.</p>').addTo(overlay);});}
  L.polygon(B.site,{color:'#263d39',weight:2.4,fillColor:'#fff0ac',fillOpacity:.9,renderer:canvas}).on('click',()=>open('P')).addTo(overlay);overlay.addTo(api.group);
  $('ppl-list').innerHTML='';D.tags.filter(allowed).forEach(t=>{const col=colors[t.area];pins[t.id]=L.marker(t.at,{icon:L.divIcon({className:'ppl-pin',html:'<button style="--ppl-color:'+col+'" aria-label="'+esc(t.id+' '+t.title)+'">'+esc(t.id)+'</button>',iconSize:[36,28],iconAnchor:[18,14]}),title:t.title,zIndexOffset:3000,bubblingMouseEvents:false}).on('click',()=>open(t.id)).addTo(markers);const b=document.createElement('button');b.className='ppl-item';b.dataset.person=t.id;b.innerHTML='<strong style="color:'+col+'">'+t.id+'</strong><span>'+esc(t.title)+'<small>'+esc(t.area==='plot'?'Programme synthesis':t.area==='access'?'Access condition':'Potential users / needs to test')+'</small></span>';b.onclick=()=>open(t.id);$('ppl-list').appendChild(b);});
  markers.addTo(api.group);leaders.addTo(api.group);focus.addTo(api.group);if(selected&&allowed(D.tags.find(t=>t.id===selected)))highlight(selected);if(window.JuryStories)JuryStories.overview('people',mode);declutter();
 }
 function declutter(){if(!active)return;leaders.clearLayers();const occupied=[];D.tags.filter(allowed).forEach(t=>{const pin=pins[t.id];if(!pin)return;const o=api.map.latLngToContainerPoint(t.at);let p=o;for(const v of [[0,0],[45,-25],[-45,-25],[45,25],[-45,25],[0,40],[0,-40]]){const q=o.add(v);if(!occupied.some(a=>Math.abs(a.x-q.x)<43&&Math.abs(a.y-q.y)<34)){p=q;break;}}occupied.push(p);pin.setLatLng(api.map.containerPointToLatLng(p));if(p.distanceTo(o)>1)L.polyline([t.at,pin.getLatLng()],{color:colors[t.area],weight:1,dashArray:'2 3',interactive:false,renderer:canvas}).addTo(leaders);});}
 function highlight(id){focus.clearLayers();const t=D.tags.find(t=>t.id===id);if(t)L.circleMarker(t.at,{radius:22,fill:false,color:colors[t.area],weight:2,interactive:false,renderer:canvas}).addTo(focus);panel.querySelectorAll('[data-person]').forEach(b=>b.classList.toggle('selected',b.dataset.person===id));}
 function open(id){const t=D.tags.find(t=>t.id===id);if(!t)return;selected=id;highlight(id);$('ppl-detail').innerHTML='<button id="ppl-back">← All user tags</button><h3>'+esc(t.id+' · '+t.title)+'</h3><p class="ppl-status">Potential users · need and trip not confirmed</p>'+[['Who / possible origin','who'],['Evidence we have','fact'],['Reason to come · hypothesis','need'],['When · scenario','time'],['Arrival and obstacles','access'],['Design consequence to test','design'],['What would confirm or reject this','test']].map(([h,k])=>'<h4>'+h+'</h4><p>'+esc(t[k])+'</p>').join('')+'<p class="ppl-small">'+t.sources.map(id=>'<a href="'+esc(D.sources[id].url)+'" target="_blank" rel="noopener">'+esc(D.sources[id].title)+'</a>').join(' · ')+'</p>';if(window.JuryStories)JuryStories.detail('people',id,document.getElementById('ppl-detail'));$('ppl-back').onclick=()=>{selected=null;$('ppl-detail').innerHTML='';highlight(null);};$('ppl-body').hidden=false;$('ppl-collapse').setAttribute('aria-expanded','true');$('ppl-collapse').textContent='−';panel.scrollTop=Math.max(0,$('ppl-detail').offsetTop-panel.querySelector('header').offsetHeight-8);}
 Object.values(D.sources).forEach(s=>{const p=document.createElement('p');p.innerHTML='<a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a><small>'+esc(s.date)+'</small><small>'+esc(s.scope)+'</small>';$('ppl-source-list').appendChild(p);});
 panel.querySelectorAll('[data-origin]').forEach(b=>b.onclick=()=>{mode=b.dataset.origin;selected=null;$('ppl-detail').innerHTML='';panel.querySelectorAll('[data-origin]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();fit();panel.scrollTop=0;});
 panel.querySelectorAll('[data-ppl-layer]').forEach(c=>c.onchange=()=>{visible[c.dataset.pplLayer]=c.checked;draw();});
 $('ppl-fit').onclick=fit;$('ppl-plot').onclick=()=>{api.map.fitBounds(L.latLngBounds(B.site).pad(2),{...pad(),animate:false,maxZoom:19});open('P');};
 $('ppl-collapse').onclick=function(){const b=$('ppl-body');b.hidden=!b.hidden;this.setAttribute('aria-expanded',String(!b.hidden));this.textContent=b.hidden?'+':'−';};
 api.map.on('zoomend moveend',declutter);
 if(window.JuryStories)JuryStories.mount('people',panel);
 return {draw,fit,open,show(on){active=on;panel.hidden=key.hidden=caption.hidden=!on;document.body.classList.toggle('people-on',on);if(on){api.map.invalidateSize();draw();}},stats(){return {active,mode,tags:Object.keys(pins),selected,layers:{...visible}};}};
};
