/* Research interpretation only. No individual residents, population estimates or survey writes. */
window.PEOPLE_DATA = {
  version:'2026-09-14-1',
  sources:{
    brief:{title:'Studio brief & programme',url:'people-research.html#programme',date:'Fall 2026',scope:'Official course programme, transcribed in COURSE_BRIEF.md and PROGRAM.md; not a demand study.'},
    survey:{title:'Existing building-use records',url:'people-research.html#local-evidence',date:'September 2026 project copy',scope:'Selected recorded uses; approximate map assignments. No interviews, household census or current business audit.'},
    osm:{title:'OpenStreetMap source bridge',url:'https://www.openstreetmap.org/way/701135687',date:'Preserved 2026-09-13 extract',scope:'Mapped roads, bridge and stairs; not verified walking accessibility.'},
    municipal:{title:'Municipality · work and mixed activities',url:'https://bourjhammoud.gov.lb/?q=ar%2Fnode%2F323',date:'Undated; indexed page checked 2026-09-14',scope:'District-level account of shops, homes and workshops. No present-day counts adopted.'},
    strategy:{title:'Municipal study · communal services',url:'https://www.bourjhammoud.gov.lb/sites/default/files/public/SBH-REPORT-F-shrinked.pdf',date:'Historical study; publication date VERIFY',scope:'Sections E.1–E.2, printed pp.18–19; historical training/services context, not current unmet demand.'},
    sugar:{title:'Sugar Rush · BCP address and production',url:'https://sugar-rush.tv/about/',date:'Undated page checked 2026-09-14',scope:'Self-described media production at BCP, Seaside Road. No partnership, staff count or need for coworking established.'},
    social:{title:'Mouvement Social · Bourj Hammoud centre',url:'https://mouvementsocial.org/centers/Bourj%20Hammoud',date:'Undated page checked 2026-09-14',scope:'Existing training/community organisation on Al Masaken Street. Not placed as an exact pin in this extract.'},
    yfc:{title:'YFC Lebanon · vocational training',url:'https://yfclebanon.org/vocational-training-program/',date:'Programme began 2019; page checked 2026-09-14',scope:'Provider describes computer, sewing and language programmes; religious provider, not a neutral district census.'},
    nabaa:{title:'UN-Habitat · Nabaa profile and strategy',url:'https://unhabitat.org/sites/default/files/documents/2019-08/un-habitat_2017.05.08_nps_nabaa_web.pdf',date:'2017; livelihoods recommendations, printed p.32',scope:'Indexed excerpt reviewed. Nabaa is a different subarea; recommendations are not current demand at our plot.'},
    ifpo:{title:'Ifpo · Aswat workshop programme',url:'https://www.ifporient.org/wp-content/uploads/2025/10/Aswat2025-Programme-EN_WEB.pdf',date:'November 2025 event',scope:'Historical cultural/learning activity at Royal Cinema and surroundings. Not a current schedule or a route to this plot.'},
    forum:{title:'Forum de Beyrouth · address',url:'https://forum.ws/?page_id=16',date:'Undated page checked 2026-09-14',scope:'Charles Helou Avenue, Medawar. Event attendance and spillover to the project unknown.'},
    profiling:{title:'UN-Habitat / UNICEF · area-based profiling',url:'https://lebanonportal.unhabitat.org/',date:'Methodology page checked 2026-09-14',scope:'Local area-based evidence matters; district averages cannot identify individual building occupants.'}
  },
  zones:[
    {id:'south',color:'#307c67',title:'SOUTH / LOWER · homes + shops + workshops',at:[33.8927,35.5428],ring:[[33.89605,35.5377],[33.8948,35.5426],[33.8935,35.5481],[33.8912,35.5481],[33.8912,35.5361],[33.8941,35.5371]]},
    {id:'near',color:'#b16c32',title:'NEARBY · mixed working frontages',at:[33.8972,35.5442],ring:[[33.89815,35.5386],[33.89772,35.542],[33.8958,35.5481],[33.89485,35.5481],[33.89615,35.5414],[33.89665,35.5384]]},
    {id:'north',color:'#7153a1',title:'NORTH / UPPER · business + production',at:[33.9005,35.5442],ring:[[33.89885,35.5396],[33.90165,35.5405],[33.90165,35.5481],[33.89665,35.5481],[33.8978,35.5421]]},
    {id:'west',color:'#367f9c',title:'WEST / LEFT · across the river',at:[33.9001,35.5357],ring:[[33.9016,35.5347],[33.9016,35.5382],[33.8984,35.5368],[33.8955,35.5352],[33.8955,35.5347]]}
  ],
  routes:[
    {id:'south',title:'Southern approach components',color:'#307c67',ways:[306996681,715531021,701135687,701135688,270786366],note:'Street 52 + mapped footbridge/stairs. Not a verified continuous or step-free walk.'},
    {id:'north',title:'Northern approach component',color:'#7153a1',ways:[275315121],note:'Street 80 on the plot side. Individual business entrances and final plot entry TBD.'},
    {id:'west',title:'Cross-river component only',color:'#367f9c',ways:[452148075,452148076],note:'Armenia road bridge. Onward route to the plot is not established; no river shortcut drawn.'}
  ],
  tags:[
    {id:'P',area:'plot',at:[33.89654,35.54112],title:'Who should this hub serve first?',who:'First test: nearby residents, small-business/workshop users and learners. Secondary test: business/creative users and booked visitors.',fact:'The brief requires public, cultural, business, learning and productive/ecological functions. It does not establish who will attend.',need:'A useful shared destination for learning, presenting work, meeting and taking a break—not just a building visible from the highway.',time:'Recurring local use is the priority hypothesis; session and event peaks are secondary. No attendance forecast.',access:'The plot-side street and highway crossing are potential arrival interfaces. Final entrance and step-free approach remain TBD.',design:'Put an easy-to-find welcome and sheltered pause near arrival; connect learning, shared work and exhibition. Give quiet work separation from noisy demonstrations and servicing.',test:'Ask each potential group what they currently use, what is missing, and what would make them return. Reject functions with no additional value.',sources:['brief','survey']},
    {id:'S1',area:'south',at:[33.89475,35.54025],title:'Lower side: nearby residents',who:'People living in the mixed blocks south of the highway; age, household composition and numbers unknown.',fact:'Existing records include mixed-use buildings with shops at ground level. This supports a resident-and-trade context, not a resident census.',need:'Test demand for informal learning, a place to meet and a sheltered pause without requiring a café purchase.',time:'After-school, after-work and weekend use are scenarios to ask about—not measured peaks.',access:'Local streets can lead toward Street 52 and the mapped footbridge. Stairs may change who can use that approach.',design:'A legible shared entrance, seating, toilets and flexible learning space should work independently of paid offices. Avoid promising childcare or a school not in the brief.',test:'Do residents actually travel this way? Which activities would justify crossing the highway? Would fees or stairs prevent attendance?',sources:['survey','osm','brief']},
    {id:'S2',area:'south',at:[33.8937,35.5436],title:'Lower side: makers, traders and learners',who:'Workshop owners, employees, shopkeepers and prospective trainees—not all residents, and not all the same group.',fact:'The municipal account describes small workshops alongside shops and housing. Recorded southern mixed-use cards include workshop ground floors.',need:'Test shared product display, practical short courses, digital presentation and bookable small meetings—not replacement of existing workshops.',time:'Short visits between tasks; scheduled sessions outside work commitments. Exact hours TBD.',access:'Carrying products or tools makes stairs and delivery arrangements important; a nearby straight-line distance is not enough.',design:'Join demonstration → documentation/meeting → small exhibition or sale. Separate material handling and dust/noise from quiet desk work.',test:'What equipment or service cannot be accessed now? Can businesses release staff? Who would teach, pay and maintain shared equipment?',sources:['municipal','survey','nabaa']},
    {id:'N1',area:'near',at:[33.89708,35.54183],title:'Same side: workshop and service staff',who:'Staff, owners and visiting customers of the immediate commercial/workshop frontages.',fact:'Original records 145 and 149 have workshop/light-industry ground uses; record 207 already has a café/restaurant use. Placements are approximate.',need:'Test convenient short-break seating, support amenities and bookable learning/meeting space. Do not claim there is no café nearby.',time:'Before work, brief breaks and shift-end visits are interview scenarios. Working hours and break lengths unknown.',access:'Some destinations share the north side of the highway with the project; that avoids this highway crossing, not every street conflict.',design:'Keep short-stay functions easy to reach without passing through controlled coworking areas. Put delivery and public waiting in separate paths.',test:'Would people leave their workplace at all? What does the existing café already provide? Is a shared room more useful than another food offer?',sources:['survey','brief']},
    {id:'N2',area:'north',at:[33.8977,35.543],title:'Upper side: creative and business users ≈',who:'Potential users linked to nearby business/production activity, including independent collaborators—not assumed office tenants.',fact:'Sugar Rush lists BCP Business & Creative Park, Seaside Road, and describes media production. This pin represents approximate context, not a verified entrance.',need:'Test small project meetings, product photography/presentation sessions, mentoring and public showcases. Existing companies may already have everything they need.',time:'Booked weekday sessions and occasional public events are a possible operating pattern, not documented demand.',access:'Street 80 is the local approach component. Routes from individual offices and entrance positions remain VERIFY.',design:'Connect a controlled quiet-work layer to shared meeting/exhibition rooms. Do not turn the entire public ground floor into an office lobby.',test:'What facilities are missing outside their premises? Would companies work with local makers? No collaboration agreement exists.',sources:['sugar','brief']},
    {id:'N3',area:'north',at:[33.89858,35.5409],title:'Homes and workshops also exist north',who:'Residents and small traders in the northern mixed frontage cluster.',fact:'Original records 97 and 109 combine mixed use with workshop ground floors; 105 is recorded residential. Locations remain provisional.',need:'The same local-learning and shared-space questions apply here. Do not allocate all community use to the southern side.',time:'Different home and work schedules can overlap within the same block; timetable unknown.',access:'Some users may approach without crossing the main highway, but their precise street route still matters.',design:'An entrance should welcome both directions. North/south shading must not become a rigid split between “business people” and “community people”.',test:'Check the recorded uses in person and ask which side residents actually enter from.',sources:['survey','municipal']},
    {id:'W1',area:'west',at:[33.89765,35.53535],title:'Across the river: occasional visitors ≈',who:'Potential visitors from Beirut/Medawar/Karantina, including people making a specifically planned trip.',fact:'Forum de Beyrouth is listed on Charles Helou Avenue, Medawar. A destination across the river does not establish spillover into our project.',need:'A particular exhibition, workshop or meeting could motivate a visit; ordinary passing traffic is not proof.',time:'Event-based demand is conditional. No event calendar, attendance transfer or commuter estimate is claimed.',access:'The river bridge and an onward connection must be considered separately from crossing the highway. No direct river-to-plot path is drawn.',design:'Make a small event space independently operable, but do not size the whole project around unproven regional crowds.',test:'Would a specific event attract people across the river? Which route/mode would they use? Could an existing venue already host it?',sources:['forum','osm','brief']},
    {id:'C1',area:'access',at:[33.89606,35.54093],title:'Who is excluded by the approach?',who:'Anyone for whom stairs or an interrupted pavement are difficult: mobility-aid users, people carrying goods, carers with pushchairs and others.',fact:'The saved OSM bridge has associated stair geometries. A usable step-free alternative has not been established.',need:'Access is part of the user brief, not an issue to postpone until the internal lift is designed.',time:'Check daytime and after-dark arrival. No present lighting or safety rating assigned.',access:'The bridge exists in source data; its present access and landing-to-street continuity require field checking.',design:'Test an accessible arrival from the wider network as well as internal circulation. A lift inside the building cannot fix an inaccessible route outside it.',test:'Walk the alternatives with a measured checklist: curbs, slopes, steps, obstructions and gates. Do not label this a wheelchair-accessible route yet.',sources:['osm','brief']},
    {id:'E1',area:'near',at:[33.89685,35.54475],title:'East: customers are not automatically users',who:'People already visiting the surrounding shops and service businesses; origins unknown.',fact:'Commercial frontage records exist near the project. Customer numbers, modes and trip chains are not recorded.',need:'A display, learning session or convenient meeting could extend a visit. The building needs a reason to stop, not only a prominent façade.',time:'Service-appointment and shopping rhythms are TBD; do not assume all-day footfall.',access:'Trace local frontage access and crossings, not the highway centreline. East-side crossing choices belong to the Connections study.',design:'Put visible activities at the public edge; avoid large programme commitments based on speculative passing trade.',test:'Ask whether visitors combine destinations, their available time and whether they arrive walking or by vehicle.',sources:['survey','municipal']},
    {id:'Q1',area:'north',at:[33.90135,35.54555],title:'Further north: waterfront workers?',who:'Possible workers and users beyond the current northern map boundary. Not yet established as a project catchment.',fact:'The detailed map ends before the actual shoreline. The brief mentions an industrial/logistical waterfront, but the drawing cannot locate its users.',need:'Do not assume port/logistics staff can leave premises or walk here during breaks.',time:'Shifts, permissions and spare time unknown.',access:'This is a boundary/question tag, NOT a destination, workplace or shoreline pin.',design:'Keep any waterfront-user claim conditional until an actual workplace, exit and viable trip are identified.',test:'Locate accessible destinations on a wider base, then establish a reason to visit. Do not count waterfront users in the primary demand case yet.',sources:['brief','osm']},
    {id:'S3',area:'south',at:[33.89205,35.5394],title:'Learning: add value to existing provision',who:'Potential learners and partner organisations from the wider district; no exact school/centre catchment assigned.',fact:'Mouvement Social and YFC describe existing training in Bourj Hammoud. A 2025 Ifpo programme documents cultural learning activity. These are district references, not pins at this tag.',need:'Test complementary short sessions and shared resources. “There are no learning or cultural spaces” is not a defensible claim.',time:'A timetable should be negotiated with existing providers and learners. No operating agreement or current capacity audit exists.',access:'This tag is an analytical district-context anchor; the providers are not geolocated here and some lie beyond the detailed base.',design:'Use flexible workshop/event rooms for supplementary provision, not an invented replacement institution. The ecological programme needs actual facilitators and recurring use.',test:'Ask providers what they cannot currently offer, their fees, reach and availability. Ask learners separately—provider views alone are insufficient.',sources:['social','yfc','ifpo','nabaa']}
  ]
};
