/* Read-only research stations. Positions are discussion anchors, never sensors or new buildings. */
window.PROTECTION_DATA={
 version:'2026-09-15-1',center:[33.89653,35.54112],
 sources:{
  map:{title:'Preserved OSM geometry · 2026-09-13',url:'https://www.openstreetmap.org/copyright',scope:'Local archived geometry establishes relative position, not environmental performance.'},
  course:{title:'Studio site-analysis lecture · environmental questions',url:'protection-research.html#course',scope:'Course brief: investigate sun, wind, heat, dust, noise and comfortable thresholds. Not field measurements.'},
  noise:{title:'FHWA · noise analysis and abatement guidance',url:'https://www.fhwa.dot.gov/Environment/noise/regulations_and_guidance/analysis_and_abatement_guidance/polguide05.cfm',scope:'Barrier mechanisms and limitations; US technical guidance, not Lebanese compliance or a site prediction.'},
  air:{title:'US EPA · Near Roadway Air Pollution FAQ (2014)',url:'https://www.epa.gov/sites/default/files/2015-11/documents/420f14044_0.pdf',scope:'Dispersion and design mechanisms; no local concentrations or reduction percentages inferred.'},
  beirut:{title:'Al Aawar et al. · Beirut generator dispersion (2021 preprint)',url:'https://arxiv.org/abs/2111.07635',scope:'City modelling study; not monitoring at our plot. Building geometry, weather and emission assumptions matter.'},
  climate:{title:'NASA POWER · meteorological data FAQ',url:'https://power.larc.nasa.gov/docs/faqs/data/',scope:'Gridded meteorological products are not on-plot wind observations.'},
  solar:{title:'NOAA · solar-position equations',url:'https://gml.noaa.gov/grad/solcalc/solareqns.PDF',scope:'Geometric sun direction only. Our seasonal demonstration uses fixed declinations and solar time, not clock time.'},
  heat:{title:'US EPA · benefits of trees and vegetation',url:'https://www.epa.gov/heatislands/benefits-trees-and-vegetation',scope:'Shade and evapotranspiration mechanisms; no cooling magnitude applied to this site.'},
  water:{title:'US EPA · green infrastructure and groundwater protection',url:'https://www.epa.gov/green-infrastructure/green-infrastructure-and-groundwater-protection',scope:'Infiltration requires groundwater and contamination assessment. US guidance is not a local design approval.'},
  soil:{title:'US EPA · brownfields and urban agriculture FAQ',url:'https://www.epa.gov/brownfields/frequent-questions-about-brownfields-and-urban-agriculture',scope:'Prior use and testing matter. A vacant or industrial-context site is not automatically contaminated.'},
  drainage:{title:'UN-Habitat · Maraach urban interventions (2022)',url:'https://unhabitat.org/news/09-nov-2022/urban-october-in-beirut-improving-life-through-urban-interventions',scope:'District example of drainage/lighting work, not evidence of flooding on our plot.'},
  access:{title:'Our whole-journey accessibility study',url:'accessibility-research.html',scope:'Source-mapped street/bridge relationships and unresolved entrance levels; no certified route.'}
 },
 lenses:{
  all:{name:'Overview · separate the pressures',color:'#495f57',ids:null,title:'Protection is selective, not one sealed enclosure.',text:'Our plot sits north of the main highway, west of Street 80 and east of the river. Those relationships are established; the intensity and timing of each exposure are not. Read six different mechanisms before choosing one form.'},
  noise:{name:'1 · Noise / ground to roof',color:'#ad4944',ids:['P','N1','N2','C1','E1'],title:'Test a quieter interior in section, not just in plan.',text:'The southern highway is a source corridor to investigate. A shield that helps seated people may not screen upper rooms; entrances and open ends also matter. Neither decibels nor a quiet zone have been measured.'},
  air:{name:'2 · Air, dust & odour',color:'#b2762a',ids:['P','A1','A2','W1','W2','C1','E1'],title:'A quieter courtyard is not automatically cleaner.',text:'Compare road-facing edges, the inner plot and proposed intake heights under different winds. Locate actual idling, exhaust and workshop sources before assigning air quality. No plume or clean-air refuge is asserted.'},
  solar:{name:'3 · Sun, glare & heat',color:'#a16b15',ids:['P','S1','S2','C1','E1'],title:'Shade people, not just the drawing.',text:'Season, hour, height and neighbouring massing alter direct sun. Shade, ventilation and hot surrounding surfaces are separate comfort tests. The sun ray is geometry only; there is no temperature or building-shadow prediction.'},
  wind:{name:'4 · Wind / ventilation',color:'#2c7886',ids:['P','W1','W2','A2','C1','E1'],title:'Keep useful airflow without assuming it is clean.',text:'Directional what-if cases test openings and shelter. Regional desk data cannot establish local speed, turbulence or frequency. Ground level and roof level need separate checks; calm conditions matter too.'},
  water:{name:'5 · Rain, drainage & ground',color:'#446b9d',ids:['P','R1','R2','G1','E1'],title:'Separate falling rain, street runoff and river risk.',text:'The river is mapped, but a river outline is not a flood extent. Plot levels, drains, groundwater and soil quality remain unknown. A dry accessible threshold and an overflow strategy must be developed together.'},
  traffic:{name:'6 · Traffic & visual exposure',color:'#775b87',ids:['P','T1','T2','V1','V2'],title:'Protect the arrival without hiding it.',text:'Street 80 is an approach and vehicle interface, not an automatically safe doorstep. Test waiting, servicing, visibility and privacy in section and at different hours. Exposure does not by itself demonstrate crime or danger.'}
 },
 roads:[{id:200611932,title:'Southern highway · mapped carriageway',topics:['noise','air','traffic']},{id:237737315,title:'Southern highway · mapped carriageway',topics:['noise','air','traffic']},{id:692409629,title:'Highway continuation',topics:['noise','air','traffic']},{id:26316545,title:'Sea Road · northern context',topics:['noise','air','traffic']},{id:275315121,title:'Street 80 · local interface',topics:['noise','air','traffic']},{id:701135687,title:'Mapped pedestrian bridge · elevated context',topics:['traffic']}],
 windows:[
  {id:'south',name:'Southern highway interface to inspect',topics:['noise','air','traffic'],ring:[[33.8961,35.54055],[33.89636,35.54055],[33.89636,35.54155],[33.8961,35.54155]]},
  {id:'plot',name:'Plot microclimate and ground investigation',topics:['solar','wind','water'],ring:[[33.89625,35.54085],[33.8968,35.54085],[33.8968,35.54138],[33.89625,35.54138]]},
  {id:'arrival',name:'Street 80 / entrance interface to inspect',topics:['traffic','water','air'],ring:[[33.89628,35.54126],[33.89715,35.54126],[33.89715,35.54165],[33.89628,35.54165]]}
 ],
 tags:[
 {id:'P',at:[33.89653,35.54112],title:'Our plot · different layers for different tasks',fact:'Corrected plot geometry places the site between the southern highway interface and Street 80. No existing protected inner court has been demonstrated.',meaning:'The same plot edge can be acoustically exposed, useful for access and important for ventilation. A single good/bad colour cannot resolve those roles.',design:'Test an accessible sheltered threshold, a selective buffer and a shared inner space. Keep openings adjustable; compare at least two orientations before fixing the nest.',check:'VERIFY ground and roof sections, entrance levels, simultaneous exposure observations and neighbouring heights.',sources:['map','course']},
 {id:'N1',at:[33.8962,35.54105],title:'Highway sound · source to receiver',fact:'Source ways identify main highway carriageways south of the plot. Traffic composition, level relative to the site and sound levels are TBD.',meaning:'Distance alone cannot establish which rooms will be protected; receiver height, openings and the geometry between road and listener need to be tested.',design:'Compare road-facing buffer depth and courtyard openings using ground/upper-room sections. Do not allocate all quiet uses from a plan-distance band.',check:'Record paired road-edge/inner-site sound observations and traffic events in comparable morning, afternoon and evening periods; calibrated measurements before performance claims.',sources:['map','noise']},
 {id:'N2',at:[33.89792,35.54145],title:'Northern context · not a silent back',fact:'Sea Road is mapped to the north and Street 80 links the context around the site. Present sound contribution from either is unmeasured.',meaning:'Turning away from the main highway does not prove that a northern opening is quiet. Local movements and operating hours may change the preferred orientation.',design:'Compare a northern opening with a staggered eastern opening; retain a way to close or acoustically separate shared space from sensitive rooms.',check:'Compare source signatures at all accessible plot sides, including deliveries, horns and intermittent machinery, without assuming the source from sound alone.',sources:['map','noise']},
 {id:'A1',at:[33.89613,35.54142],title:'Traffic air / dust · do not draw an invented plume',fact:'The highway and local road are potential traffic-emission corridors. Vehicle counts, PM, NO₂, dust deposition and odour sources on this plot are not measured.',meaning:'The pressure is plausible; its concentration and direction are not established. A coloured distance halo would falsely imply measured exposure.',design:'Keep long-stay waiting and fresh-air intake candidates away from immediate idling/loading interfaces where feasible; compare alternatives rather than label one clean.',check:'Log source activity with wind/time; use qualified monitoring for pollutant comparisons. Smell or visible dust alone is not a complete air-quality measure.',sources:['map','air']},
 {id:'A2',at:[33.89658,35.54142],title:'Exhaust and intakes · three-dimensional separation',fact:'There is no verified inventory of nearby generator stacks, workshop outlets, kitchen exhaust or operating schedules. This tag is a task location, not a found generator.',meaning:'A higher intake is not automatically outside a plume. Our project could also become a source affecting neighbours or its own courtyard.',design:'Reserve coordinated locations for intake, exhaust and servicing; test discharge height/direction and re-entry under several weather cases.',check:'Locate and date actual sources from lawful observation; obtain operating and mechanical information. Do not invent emissions from building use labels.',sources:['beirut','air']},
 {id:'S1',at:[33.89657,35.54088],title:'West side · afternoon shade test',fact:'The plan is north-up. Sun position changes with season and solar hour. Current facade heights, canopy sizes and material temperatures are not complete.',meaning:'Western afternoon exposure is a design test, not proof that the entire plot is unshaded. A roof overhang that works at noon may leave low-angle sun exposed.',design:'Compare vertical/angled screens, trees and covered circulation with seasonal sun geometry. Preserve winter light where useful.',check:'Survey surrounding heights and test morning/noon/afternoon shadows with the corrected model; observe shade at the occupied height.',sources:['solar','course']},
 {id:'S2',at:[33.89679,35.54115],title:'Neighbours, canopy and thermal comfort',fact:'Building outlines and green map polygons exist, but they do not supply reliable roof heights, canopy spread or surface temperatures.',meaning:'Green colour does not equal shade; a shaded place can still be uncomfortable through hot surfaces and weak airflow.',design:'Set a day-one shade strategy plus a mature planting strategy. Evaluate pedestrian shade and useful daylight separately from roof/greenhouse solar needs.',check:'Record actual shade, air movement, surface conditions and occupancy; use an appropriate thermal-comfort assessment before claiming a cooling amount.',sources:['heat','solar']},
 {id:'W1',at:[33.89688,35.5406],title:'Wind scenarios · regional is not on-site',fact:'Earlier desk notes use SW/WSW and NNW seasonal directions. They are not a measured on-site wind-frequency distribution.',meaning:'Nearby masses and openings may change speed and direction. A sea/river-facing opening cannot be assumed to deliver useful or clean ventilation.',design:'Compare SW, WSW, NNW and calm cases. Vary opening position/porosity and avoid treating the chosen scenario as the prevailing condition.',check:'Obtain a documented climate series and directional frequencies; measure local wind at pedestrian and proposed roof levels and validate any airflow model.',sources:['climate','beirut']},
 {id:'W2',at:[33.89638,35.54119],title:'Shelter versus stagnation',fact:'No measured airflow field exists inside the proposed project because its geometry is not yet fixed.',meaning:'A more enclosed nest may shelter one place while reducing its exchange with surrounding air. Noise and ventilation goals can conflict.',design:'Compare offset openings, a shaded permeable court and closable inner rooms. Test calm conditions and incoming air quality, not just attractive arrows.',check:'Use massing alternatives with explicit boundary conditions; test hot still periods as well as useful breezes. No ventilation rate is claimed yet.',sources:['climate','air']},
 {id:'R1',at:[33.89643,35.5388],title:'River context ≠ plot flood extent',fact:'The river corridor is mapped west of the plot. Plot flood depths, bank levels and any hydraulic connection are not established here.',meaning:'River flooding, intense-rain runoff and drainage backflow are different mechanisms. Proximity alone cannot provide a safe finished floor level.',design:'Keep a ground-risk decision open until a level/drainage survey and applicable flood information are checked; protect critical equipment without blocking access.',check:'VERIFY authoritative flood information, site/road/outfall levels and recorded local flood history. Do not sketch a flood boundary from the river polygon.',sources:['map','water']},
 {id:'R2',at:[33.89636,35.5413],title:'Wet arrival · rain and runoff',fact:'Street 80 follows the eastern/southern interface; kerb, drain and entrance invert levels are not measured. District drainage interventions are not proof of plot flooding.',meaning:'A threshold can be shaded yet become unusable in rain. Raising it casually may exchange drainage protection for an access barrier.',design:'Develop covered waiting, a continuous accessible entrance and a visible safe overflow concept together, after levels are known. Keep roof discharge away from the walking line.',check:'Observe rainfall safely; record puddles and blocked inlets from accessible places. Survey levels and receiving drainage capacity before sizing or directing flows.',sources:['map','drainage','access']},
 {id:'G1',at:[33.89669,35.54109],title:'Ground and growing · test before infiltration',fact:'Industrial surroundings do not establish soil contamination. Soil profile, contamination, groundwater, bearing capacity and infiltration suitability are TBD.',meaning:'Vegetation already growing on a plot does not certify food-growing or infiltration safety. Groundwater and contaminants can affect water-management choices.',design:'Keep alternatives for controlled growing media, lined storage and approved drainage. Do not commit to edible in-ground planting or soakaways before site investigation.',check:'Review prior uses and commission qualified geotechnical/environmental assessment and relevant water/soil tests; define greenhouse water quality and maintenance.',sources:['soil','water']},
 {id:'T1',at:[33.89688,35.54148],title:'Street 80 · doorstep versus vehicle edge',fact:'The preserved way is a mapped one-way tertiary road. It does not establish clear pedestrian width, current speed, stopping behaviour or legal access.',meaning:'An entry facing this road still needs a protected last few metres; the less major road is not automatically safe or comfortable.',design:'Separate waiting and walking from loading/turning; place a legible entrance within a sheltered threshold without forcing a detour or stairs.',check:'Observe actual vehicle/pedestrian conflicts and loading; verify driveway permissions, levels and clear routes with the accessibility study.',sources:['map','access']},
 {id:'T2',at:[33.89635,35.54104],title:'Bridge landing · shelter without a bottleneck',fact:'A pedestrian bridge and steps are source-mapped near the southern interface. Current landing dimensions and step-free alternatives remain unresolved.',meaning:'A protective wall or planting scheme could obstruct the arrival it is meant to improve. A bridge deck is not itself evidence of inclusive access.',design:'Keep the landing and onward approach legible and clear. Test canopy supports, queues and service movements outside the usable route.',check:'Measure accessible clearances and movement at the landing; coordinate any off-site proposal rather than assume permission.',sources:['map','access']},
 {id:'V1',at:[33.8961,35.54073],title:'Seen from above · privacy in section',fact:'The bridge and surrounding buildings introduce elevated viewpoints. Their current eye levels and sightlines to proposed rooms are not surveyed.',meaning:'A plan enclosure may offer little privacy to an upper walkway or neighbour. Visibility can help orientation while exposing quiet activities.',design:'Compare screens, sill heights and room orientation using seated/standing and elevated sightlines. Do not equate concealment with safety.',check:'Photograph lawful public views and survey levels; distinguish verified views from illustrative sightlines and avoid assumptions about crime.',sources:['map','course']},
 {id:'V2',at:[33.89678,35.54132],title:'After dark · legibility without glare',fact:'No plot-level lighting or night-use survey has been completed. Day photographs cannot establish night comfort or safety.',meaning:'A deep protected entrance may be difficult to find after dark; bright lighting can also disturb neighbours or impair comfort.',design:'Test recognisable entry lighting, visibility between layers and independent after-hours closure, while limiting spill toward neighbours and quiet spaces.',check:'Complete an evening approach audit with users; verify operating hours, glare and lighting requirements. Do not map an unobserved danger zone.',sources:['course','access']},
 {id:'C1',at:[33.89655,35.54104],title:'Inner shared space · test the trade-offs',fact:'A nested shared space is a proposed design idea, not an existing measured refuge.',meaning:'Sound, air, sun, rain and visibility do not share a single protective boundary. The most enclosed option is not necessarily the most comfortable.',design:'Compare an open shaded court, an offset-entry court and a partly enclosed shared room. Judge each by the same environmental and access tests before choosing.',check:'Record the strengths, unresolved risks and operating needs of each option. Keep quiet-room enclosure and shared-space ventilation as separate decisions.',sources:['noise','air','heat','access']},
 {id:'E1',at:[33.89664,35.5412],title:'Roof / upper rooms · a second exposure layer',fact:'No final roof elevation, surrounding-height model or upper-level performance study is available. This marker is vertically conceptual, not a roof position.',meaning:'Ground-level protection cannot simply be copied upward. A roof may gain sunlight and views while also gaining sound, wind and exposure.',design:'Test roof gathering/growing and upper quiet rooms separately from the ground court; coordinate shade, plant, intakes, rain collection and maintenance access.',check:'Build paired ground/upper sections with verified heights. Test structure, water quality and operations before claiming a protected or productive roof.',sources:['noise','beirut','solar','water']}
 ]
};
window.protectionSolar=function(season,hour){const r=Math.PI/180,lat=33.89653*r,d=({summer:23.44,equinox:0,winter:-23.44}[season])*r,H=(Number(hour)-12)*15*r;return{altitude:Math.asin(Math.sin(lat)*Math.sin(d)+Math.cos(lat)*Math.cos(d)*Math.cos(H))/r,azimuth:(Math.atan2(Math.sin(H),Math.cos(H)*Math.sin(lat)-Math.tan(d)*Math.cos(lat))/r+180+360)%360};};
