/* Independent, read-only environmental investigation. No survey storage or sync writes. */
window.createProtection=function(api){
 'use strict';
 const D=window.PROTECTION_DATA,B=window.PICTURES_NEW_DATA,C=window.CONNECTIONS_DATA,renderer=L.canvas({padding:.35});
 const base=L.layerGroup(),overlay=L.layerGroup(),pins=L.layerGroup(),leaders=L.layerGroup(),focus=L.layerGroup();
 let active=false,built=false,lens='all',sourceOnly=false,windows=true,season='summer',hour=12,wind='225',selected=null,markers={},rayCount=0;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shell=document.getElementById('map').parentElement,panel=document.createElement('section');panel.id='protection-panel';panel.hidden=true;panel.setAttribute('aria-label','Protection investigations');
 panel.innerHTML='<header><div><h2>Protection</h2><small>06 / Selective shelter, not a sealed box</small></div><button id="pr-collapse" aria-expanded="true" aria-label="Collapse protection panel">−</button></header><div id="pr-body"><p class="pr-status">DESK ANALYSIS · PERFORMANCE NOT MEASURED</p><label class="pr-select">Separate investigations<select id="pr-lens">'+Object.entries(D.lenses).map(([id,v])=>'<option value="'+id+'">'+esc(v.name)+'</option>').join('')+'</select></label><div id="pr-summary" aria-live="polite"></div>'+
 '<div id="pr-sun-controls" hidden><div class="pr-pair"><label class="pr-select">Season<select id="pr-season"><option value="summer">Summer solstice</option><option value="equinox">Equinox</option><option value="winter">Winter solstice</option></select></label><label class="pr-select">Solar hour · not clock time<select id="pr-hour"><option>9</option><option selected>12</option><option>15</option></select></label></div><p id="pr-sun-result"></p><p class="pr-small">Fixed declination demonstration. Ray points TOWARD the sun. Not a building-shadow or thermal model.</p></div>'+
 '<div id="pr-wind-controls" hidden><label class="pr-select">Wind FROM · comparison only<select id="pr-wind"><option value="225">SW · 225°</option><option value="257">WSW · 257°</option><option value="337">NNW · 337°</option><option value="calm">Calm / variable · no directional ray</option></select></label><p class="pr-small">What-if cases from earlier desk notes, NOT an observed wind rose, speed field or pollution plume. Arrow length is illustrative.</p></div>'+
 '<label class="pr-check"><input id="pr-source" type="checkbox"> Source geometry only · hide analysis</label><label class="pr-check"><input id="pr-windows" type="checkbox" checked> Shaded investigation windows</label><div class="pr-actions"><button id="pr-fit">Fit investigation</button><button id="pr-plot">Our plot</button></div><p class="pr-small">Coloured roads = mapped source corridors, not exposure levels. Tags = investigation stations, not sensors. Dotted leaders only move labels.</p><div id="pr-detail" aria-live="polite"></div><div id="pr-list"></div>'+
 '<details><summary>Why one protection layer is not enough</summary><table><thead><tr><th>Move to test</th><th>Also check</th></tr></thead><tbody><tr><td>Solid road-side shield</td><td>Air exchange, ends, upper floors, legible access</td></tr><tr><td>Shaded inner court</td><td>Incoming air, hot surfaces, rain and still periods</td></tr><tr><td>Trees / green screen</td><td>Actual canopy; not an assumed acoustic wall</td></tr><tr><td>Roof refuge / growing</td><td>Wind, sound, air, shade, water and maintenance</td></tr><tr><td>Raised dry threshold</td><td>Continuous accessible approach and safe overflow</td></tr></tbody></table></details>'+
 '<details><summary>What nesting would mean here</summary><ol><li>Legible, accessible and sheltered arrival.</li><li>Selective buffer: screen some exposures without closing every edge.</li><li>Shaded shared space with tested air exchange.</li><li>More controlled quiet rooms with appropriate ventilation.</li><li>Roof investigated separately, not assumed protected.</li></ol><p>These are relationships to compare, not a fixed programme or a finished plan.</p></details>'+
 '<details><summary>Priority tests before fixing the form</summary><ol><li>Paired ground/upper sections: road, bridge, neighbours and proposed receivers.</li><li>Simultaneous edge/inner-site sound, traffic and wind observations at different hours.</li><li>Source inventory and appropriate air-quality monitoring; no invented generator locations.</li><li>Corrected heights and seasonal shade comparisons.</li><li>Ground, threshold, drainage and soil/groundwater investigation.</li><li>Evening and wet-weather arrival checks.</li></ol><a href="protection-research.html#field-plan" target="_blank" rel="noopener">Full field and modelling plan ↗</a></details>'+
 '<details><summary>Limits of earlier claims</summary><p>Old CAD distance/shadow percentages are not transferred to the corrected map. Regional winds are not site measurements. Conflicting rainfall totals, flood levels, groundwater depth and contamination status remain VERIFY/TBD.</p><p>The 2021 Beirut generator preprint is by Al Aawar et al.; earlier notes misattributed it. No local plume or safe-air zone is inferred.</p></details><details><summary>Sources / evidence scope</summary><div id="pr-sources"></div></details><p><a href="protection-research.html" target="_blank" rel="noopener">Full research, sections to draw & design comparisons ↗</a></p><p class="pr-small">Original photographs, building assignments, Sun, Wind and Access studies are preserved. This new analysis does not certify environmental safety or legal compliance.</p></div>';
 shell.appendChild(panel);L.DomEvent.disableClickPropagation(panel);L.DomEvent.disableScrollPropagation(panel);
 const key=document.createElement('div');key.id='protection-key';key.hidden=true;shell.appendChild(key);L.DomEvent.disableClickPropagation(key);
 const caption=document.createElement('div');caption.id='protection-caption';caption.hidden=true;caption.innerHTML='↑ NORTH / UPPER · investigation windows ≠ hazard extents<br><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">© OpenStreetMap contributors</a> · preserved geometry';shell.appendChild(caption);
 const $=id=>document.getElementById(id),tags=()=>sourceOnly?[]:D.tags.filter(t=>!D.lenses[lens].ids||D.lenses[lens].ids.includes(t.id));
 const color=()=>D.lenses[lens].color;
 function tagColor(t){if(lens!=='all')return color();const id=t.id[0];return({N:D.lenses.noise.color,A:D.lenses.air.color,S:D.lenses.solar.color,W:D.lenses.wind.color,R:D.lenses.water.color,G:D.lenses.water.color,T:D.lenses.traffic.color,V:D.lenses.traffic.color})[id]||color();}
 function padding(){return innerWidth<700?{paddingTopLeft:[40,55],paddingBottomRight:[18,panel.offsetHeight+20]}:{paddingTopLeft:[65,65],paddingBottomRight:[panel.offsetWidth+45,65]};}
 function fit(){api.map.invalidateSize();const pts=tags().map(t=>t.at);api.map.fitBounds(pts.length?L.latLngBounds(pts).pad(.16):L.latLngBounds(D.tags.map(t=>t.at)).pad(.16),{...padding(),animate:false,maxZoom:18});}
 function build(){if(window.BuildingMap){BuildingMap.base(base,renderer);return;}if(built)return;B.base.forEach(f=>{if(!f.building&&f.polygon)L.polygon(f.polygon,{stroke:false,fillColor:f.color==='#2469b9'?'#c1d7e5':'#e6eadd',fillOpacity:1,interactive:false,renderer}).addTo(base);});B.buildings.forEach(b=>L.polygon(b.rings,{color:'#8b9898',weight:.7,fill:false,opacity:.65,interactive:false,renderer}).addTo(base));C.ways.forEach(w=>L.polyline(w.lines,{color:'#acb7b8',weight:/^(motorway|trunk)/.test(w.tags.highway)?2.5:.8,interactive:false,renderer}).addTo(base));built=true;}
 function point(at,bearing,metres){const r=bearing*Math.PI/180;return[at[0]+metres*Math.cos(r)/111320,at[1]+metres*Math.sin(r)/(111320*Math.cos(at[0]*Math.PI/180))];}
 function arrow(from,to,c,note){L.polyline([from,to],{color:c,weight:3,dashArray:'8 6',interactive:false,renderer}).addTo(overlay);const a=api.map.latLngToLayerPoint(from),b=api.map.latLngToLayerPoint(to),angle=Math.atan2(b.y-a.y,b.x-a.x);const head=[api.map.layerPointToLatLng(L.point(b.x-13*Math.cos(angle-.5),b.y-13*Math.sin(angle-.5))),to,api.map.layerPointToLatLng(L.point(b.x-13*Math.cos(angle+.5),b.y-13*Math.sin(angle+.5)))];L.polyline(head,{color:c,weight:3,interactive:false,renderer}).addTo(overlay);L.circleMarker(from,{radius:4,color:c,fillOpacity:1,renderer}).bindTooltip(note).addTo(overlay);rayCount++;}
 function draw(){if(!active)return;build();api.group.clearLayers();overlay.clearLayers();pins.clearLayers();leaders.clearLayers();focus.clearLayers();markers={};rayCount=0;base.addTo(api.group);
  if(windows&&!sourceOnly)D.windows.filter(w=>lens==='all'||w.topics.includes(lens)).forEach(w=>BuildingMap.shade(w.ring,{color:color(),weight:1,dashArray:'4 7',fillColor:color(),fillOpacity:.08,renderer,bubblingMouseEvents:false}).bindPopup('<b>'+esc(w.name)+'</b><p>Authored inspection window, not a measured hazard or protection boundary.</p>').addTo(overlay));
  D.roads.filter(r=>lens==='all'||r.topics.includes(lens)).forEach(r=>{const w=C.ways.find(w=>w.id===r.id);if(w)L.polyline(w.lines,{color:sourceOnly?'#5d7276':color(),weight:3,opacity:.9,renderer,bubblingMouseEvents:false}).bindPopup('<b>'+esc(r.title)+'</b><p>Preserved centreline/deck geometry; environmental performance unmeasured.</p><a href="https://www.openstreetmap.org/way/'+r.id+'" target="_blank" rel="noopener">Source way '+r.id+' ↗</a>').addTo(overlay);});
  L.polygon(B.site,{color:'#2b4338',weight:2.5,fillColor:'#efdfab',fillOpacity:.65,renderer,bubblingMouseEvents:false}).on('click',()=>{if(!sourceOnly)open('P');}).addTo(overlay);
  $('pr-sun-controls').hidden=sourceOnly||lens!=='solar';$('pr-wind-controls').hidden=sourceOnly||!['air','wind'].includes(lens);
  if(!sourceOnly&&lens==='solar'){const s=window.protectionSolar(season,hour);arrow(D.center,point(D.center,s.azimuth,125),color(),'Toward sun · idealised direction');$('pr-sun-result').textContent='Sun altitude '+s.altitude.toFixed(1)+'° · azimuth '+s.azimuth.toFixed(1)+'° clockwise from north.';}
  if(!sourceOnly&&['wind','air'].includes(lens)&&wind!=='calm')arrow(point(D.center,Number(wind),150),D.center,'#2c7886','Wind FROM '+wind+'° · comparison only');
  overlay.addTo(api.group);$('pr-list').innerHTML='';tags().forEach(t=>{markers[t.id]=L.marker(t.at,{title:t.title,zIndexOffset:3100,bubblingMouseEvents:false,icon:L.divIcon({className:'pr-pin',html:'<button style="--pr-col:'+tagColor(t)+'" aria-label="'+esc(t.id+' '+t.title)+'">'+t.id+'</button>',iconSize:[36,29],iconAnchor:[18,14]})}).on('click',()=>open(t.id)).addTo(pins);const b=document.createElement('button');b.className='pr-item';b.dataset.prTag=t.id;b.innerHTML='<strong style="color:'+tagColor(t)+'">'+t.id+'</strong><span>'+esc(t.title)+'</span>';b.onclick=()=>open(t.id);$('pr-list').appendChild(b);});pins.addTo(api.group);leaders.addTo(api.group);focus.addTo(api.group);
  const v=D.lenses[lens];$('pr-summary').innerHTML='<h3>'+esc(sourceOnly?'Location evidence only':v.title)+'</h3><p>'+esc(sourceOnly?'Preserved buildings, river, roads and corrected plot. All authored investigation windows, research tags and sun/wind rays are hidden. This view is not an environmental rating.':v.text)+'</p>';
  key.innerHTML='<b>PROTECTION / 06</b>'+(sourceOnly?'<span>Source geometry only · no rating</span>':(lens==='all'?Object.entries(D.lenses).filter(([id])=>id!=='all').map(([,v])=>'<span><i style="background:'+v.color+'"></i>'+esc(v.name)+'</span>').join(''):'<span><i style="background:'+color()+'"></i>'+esc(v.name)+'</span>'))+'<span><i style="background:#efdfab"></i>Our plot · location, not a safe zone</span><small>Shading: where to investigate, not intensity.<br>No measured sound / air / heat / flood map.</small>';
  if(selected&&tags().some(t=>t.id===selected))detail(selected);else{selected=null;$('pr-detail').innerHTML='';}if(window.JuryStories)JuryStories.overview('protection',lens,sourceOnly);if(window.ArchitecturalMap)ArchitecturalMap.render('protection',api,open);else declutter();
 }
 function declutter(){if(!active)return;leaders.clearLayers();const occupied=[],offsets=[[0,0]];for(let r=1;r<=9;r++)for(let x=-r;x<=r;x++)for(let y=-r;y<=r;y++)if(Math.max(Math.abs(x),Math.abs(y))===r)offsets.push([x*44,y*36]);offsets.sort((a,b)=>a[0]*a[0]+a[1]*a[1]-b[0]*b[0]-b[1]*b[1]);tags().forEach(t=>{const m=markers[t.id];if(!m)return;const origin=api.map.latLngToContainerPoint(t.at);let q=origin;for(const off of offsets){const p=origin.add(off);const size=api.map.getSize(),xmax=size.x-(innerWidth<700?24:panel.offsetWidth+40),ymax=size.y-(innerWidth<700?panel.offsetHeight+24:35),visible=origin.x>=0&&origin.x<=size.x&&origin.y>=0&&origin.y<=size.y; if(visible&&(p.x<45||p.x>xmax||p.y<65||p.y>ymax))continue;if(!occupied.some(a=>Math.abs(a.x-p.x)<42&&Math.abs(a.y-p.y)<34)){q=p;break;}}occupied.push(q);m.setLatLng(api.map.containerPointToLatLng(q));if(q.distanceTo(origin)>1)L.polyline([t.at,m.getLatLng()],{color:tagColor(t),weight:1,dashArray:'2 3',renderer,interactive:false}).addTo(leaders);});}
 function detail(id){const t=D.tags.find(t=>t.id===id);focus.clearLayers();L.circleMarker(t.at,{radius:20,color:tagColor(t),fill:false,weight:2,interactive:false,renderer}).addTo(focus);$('pr-detail').innerHTML='<button id="pr-back">← All investigation tags</button><h3>'+esc(t.id+' · '+t.title)+'</h3><p class="pr-status">RESEARCH STATION · NOT A MEASUREMENT</p><h4>Evidence / what is known</h4><p>'+esc(t.fact)+'</p><h4>Analysis / what this changes</h4><p>'+esc(t.meaning)+'</p><h4>Design comparison</h4><p>'+esc(t.design)+'</p><h4>VERIFY / next test</h4><p>'+esc(t.check)+'</p><p class="pr-small">'+t.sources.map(id=>'<a href="'+esc(D.sources[id].url)+'" target="_blank" rel="noopener">'+esc(D.sources[id].title)+'</a>').join(' · ')+'</p>';if(window.JuryStories)JuryStories.detail('protection',id,document.getElementById('pr-detail'));$('pr-back').onclick=()=>{selected=null;$('pr-detail').innerHTML='';focus.clearLayers();};panel.querySelectorAll('[data-pr-tag]').forEach(b=>b.classList.toggle('selected',b.dataset.prTag===id));}
 function open(id){if(!tags().some(t=>t.id===id))return;selected=id;detail(id);$('pr-body').hidden=false;$('pr-collapse').textContent='−';$('pr-collapse').setAttribute('aria-expanded','true');panel.scrollTop=Math.max(0,$('pr-detail').offsetTop-panel.querySelector('header').offsetHeight-8);}
 $('pr-sources').innerHTML=Object.values(D.sources).map(s=>'<p><a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a><small>'+esc(s.scope)+'</small></p>').join('');
 $('pr-lens').onchange=e=>{lens=e.target.value;selected=null;draw();fit();panel.scrollTop=0;};$('pr-source').onchange=e=>{sourceOnly=e.target.checked;draw();};$('pr-windows').onchange=e=>{windows=e.target.checked;draw();};$('pr-season').onchange=e=>{season=e.target.value;draw();};$('pr-hour').onchange=e=>{hour=Number(e.target.value);draw();};$('pr-wind').onchange=e=>{wind=e.target.value;draw();};$('pr-fit').onclick=fit;$('pr-plot').onclick=()=>api.map.fitBounds(L.latLngBounds(B.site).pad(1.8),{...padding(),animate:false,maxZoom:19});$('pr-collapse').onclick=function(){const b=$('pr-body');b.hidden=!b.hidden;this.textContent=b.hidden?'+':'−';this.setAttribute('aria-expanded',String(!b.hidden));};api.map.on('zoomend moveend',declutter);
 if(window.JuryStories)JuryStories.mount('protection',panel);
 api.map.off('zoomend moveend',declutter);
 const oldFit=fit;fit=function(){if(!window.ArchitecturalMap||!ArchitecturalMap.fit('protection',api.map,panel))oldFit();};$('pr-fit').onclick=fit;
 return{draw,fit,open,show(on){active=on;panel.hidden=key.hidden=caption.hidden=!on;document.body.classList.toggle('protection-on',on);if(on){api.map.invalidateSize();draw();}},stats(){return{active,lens,sourceOnly,windows,season,hour,wind,selected,tags:Object.keys(markers),rayCount};}};
};
